.TH MPI_File_c2f 3 "10/7/2014" " " "MPI"
.SH NAME
MPI_File_c2f \-  Translates a C file handle to a Fortran file handle 
.SH SYNOPSIS
.nf
MPI_Fint MPI_File_c2f(MPI_File fh)
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B fh 
- C file handle (handle)
.PD 1

.SH RETURN VALUE
Fortran file handle (integer)
.SH LOCATION
/tmp/nRvVJlUkeF/mpich-3.1.3/src/mpi/romio/mpi-io/file_c2f.c
