.TH MPIR_Type_struct 3 "11/21/2018" " " "MPI"
.SH NAME
MPIR_Type_struct \-  create a struct datatype 
.SH SYNOPSIS
.nf
#undef FUNCNAME
#define FUNCNAME MPIR_Type_struct
#undef FCNAME
#define FCNAME MPL_QUOTE(FUNCNAME)
int MPIR_Type_struct(int count,
                     const int *blocklength_array,
                     const MPI_Aint * displacement_array,
                     const MPI_Datatype * oldtype_array, MPI_Datatype * newtype)
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B count 
- number of blocks in vector
.PD 1
.PD 0
.TP
.B blocklength_array 
- number of elements in each block
.PD 1
.PD 0
.TP
.B displacement_array 
- offsets of blocks from start of type in bytes
.PD 1
.PD 0
.TP
.B oldtype_array 
- types (using handle) of datatypes on which vector is based
.PD 1

.SH OUTPUT PARAMETERS
.PD 0
.TP
.B newtype 
- handle of new struct datatype
.PD 1

.SH RETURN VALUE
MPI_SUCCESS on success, MPI errno on failure.
