.TH MPIR_Type_vector 3 "11/21/2018" " " "MPI"
.SH NAME
MPIR_Type_vector \-  create a vector datatype 
.SH SYNOPSIS
.nf
int MPIR_Type_vector(int count,
                     int blocklength,
                     MPI_Aint stride,
                     int strideinbytes, MPI_Datatype oldtype, MPI_Datatype * newtype)
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B count 
- number of blocks in vector
.PD 1
.PD 0
.TP
.B blocklength 
- number of elements in each block
.PD 1
.PD 0
.TP
.B stride 
- distance from beginning of one block to the next (see next
parameter for units)
.PD 1
.PD 0
.TP
.B strideinbytes 
- if nonzero, then stride is in bytes, otherwise stride
is in terms of extent of oldtype
.PD 1
.PD 0
.TP
.B oldtype 
- type (using handle) of datatype on which vector is based
.PD 1

.SH OUTPUT PARAMETERS
.PD 0
.TP
.B newtype 
- handle of new vector datatype
.PD 1

.SH RETURN VALUE
0 on success, MPI error code on failure.
