##
## Copyright (C) by Argonne National Laboratory
##     See COPYRIGHT in top-level directory
##
## DO NOT EDIT: AUTOMATICALLY GENERATED FILE !!
##

libyaksa_la_SOURCES += \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_hvector__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_blkhindx__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_hindexed__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_contig__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_resized__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_hvector__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_blkhindx__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_hindexed__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_contig__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_resized__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_hvector__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_blkhindx__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_hindexed__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_contig__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_resized__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_hvector__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_blkhindx__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_hindexed__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_contig__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_resized__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_hvector__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_blkhindx__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_hindexed__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_contig__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_resized__Bool.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_hvector_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_blkhindx_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_hindexed_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_contig_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_resized_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_hvector_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_blkhindx_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_hindexed_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_contig_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_resized_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_hvector_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_blkhindx_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_hindexed_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_contig_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_resized_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_hvector_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_blkhindx_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_hindexed_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_contig_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_resized_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_hvector_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_blkhindx_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_hindexed_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_contig_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_resized_char.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_hvector_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_blkhindx_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_hindexed_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_contig_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_resized_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_hvector_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_blkhindx_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_hindexed_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_contig_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_resized_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_hvector_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_blkhindx_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_hindexed_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_contig_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_resized_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_hvector_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_blkhindx_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_hindexed_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_contig_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_resized_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_hvector_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_blkhindx_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_hindexed_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_contig_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_resized_wchar_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_hvector_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_blkhindx_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_hindexed_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_contig_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_resized_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_hvector_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_blkhindx_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_hindexed_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_contig_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_resized_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_hvector_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_blkhindx_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_hindexed_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_contig_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_resized_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_hvector_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_blkhindx_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_hindexed_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_contig_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_resized_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_hvector_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_blkhindx_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_hindexed_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_contig_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_resized_int8_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_hvector_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_blkhindx_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_hindexed_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_contig_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_resized_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_hvector_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_blkhindx_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_hindexed_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_contig_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_resized_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_hvector_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_blkhindx_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_hindexed_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_contig_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_resized_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_hvector_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_blkhindx_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_hindexed_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_contig_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_resized_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_hvector_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_blkhindx_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_hindexed_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_contig_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_resized_int16_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_hvector_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_blkhindx_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_hindexed_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_contig_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_resized_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_hvector_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_blkhindx_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_hindexed_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_contig_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_resized_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_hvector_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_blkhindx_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_hindexed_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_contig_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_resized_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_hvector_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_blkhindx_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_hindexed_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_contig_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_resized_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_hvector_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_blkhindx_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_hindexed_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_contig_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_resized_int32_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_hvector_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_blkhindx_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_hindexed_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_contig_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_resized_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_hvector_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_blkhindx_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_hindexed_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_contig_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_resized_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_hvector_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_blkhindx_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_hindexed_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_contig_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_resized_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_hvector_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_blkhindx_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_hindexed_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_contig_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_resized_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_hvector_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_blkhindx_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_hindexed_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_contig_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_resized_int64_t.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_hvector_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_blkhindx_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_hindexed_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_contig_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_resized_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_hvector_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_blkhindx_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_hindexed_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_contig_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_resized_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_hvector_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_blkhindx_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_hindexed_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_contig_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_resized_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_hvector_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_blkhindx_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_hindexed_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_contig_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_resized_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_hvector_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_blkhindx_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_hindexed_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_contig_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_resized_float.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_hvector_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_blkhindx_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_hindexed_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_contig_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_resized_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_hvector_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_blkhindx_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_hindexed_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_contig_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_resized_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_hvector_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_blkhindx_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_hindexed_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_contig_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_resized_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_hvector_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_blkhindx_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_hindexed_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_contig_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_resized_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_hvector_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_blkhindx_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_hindexed_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_contig_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_resized_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_long_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_hvector_long_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_blkhindx_long_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_hindexed_long_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_contig_long_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hvector_resized_long_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_long_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_hvector_long_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_blkhindx_long_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_hindexed_long_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_contig_long_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_blkhindx_resized_long_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_long_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_hvector_long_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_blkhindx_long_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_hindexed_long_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_contig_long_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_hindexed_resized_long_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_long_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_hvector_long_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_blkhindx_long_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_hindexed_long_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_contig_long_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_contig_resized_long_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_long_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_hvector_long_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_blkhindx_long_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_hindexed_long_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_contig_long_double.c \
	src/backend/seq/pup/yaksuri_seqi_pup_resized_resized_long_double.c \
	src/backend/seq/pup/yaksuri_seq_pup.c

noinst_HEADERS += \
	src/backend/seq/pup/yaksuri_seqi_pup.h
