name: GH Man Page Updater

on:
  push:
    branches:
      - main
    paths:
      - 'man/*.md'
  workflow_dispatch:

jobs:
    gh-man-update:
        name: GH Man Page Updater
        runs-on: ubuntu-latest
        steps:
          - name: Debug information
            env:
              GITHUB_DATA: ${{ toJSON(github) }}
            run: |
              echo This is information that may be useful for debugging.
              echo "$GITHUB_DATA"

          - name: Check out the git repo
            uses: actions/checkout@v2

          - name: Update the man pages in branch gh-pages
            run: .github/workflows/gh-man.sh
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              REPO: ${{ github.event.repository.full_name }}
              BASE_REF: ${{ github.event.repository.default_branch }}
