# See https://aka.ms/yaml
# This pipeline to be run on PRs

trigger: none
pr:
  branches:
    include:
    - master
    - v*.*.x
  paths:
    exclude:
    - .gitignore
    - .readthedocs.yaml
    - docs/source
    - docs/CodeStyle.md
    - docs/LoggingStyle.md
    - docs/OptimizationStyle.md
    - README.md
    - NEWS
    - AUTHORS

extends:
  template: pr/main.yml
