/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_FETCH_AND_OP( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_fetch_and_op__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_fetch_and_op( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_fetch_and_op_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPIX_FETCH_AND_OP = PMPIX_FETCH_AND_OP
#pragma weak mpix_fetch_and_op__ = PMPIX_FETCH_AND_OP
#pragma weak mpix_fetch_and_op_ = PMPIX_FETCH_AND_OP
#pragma weak mpix_fetch_and_op = PMPIX_FETCH_AND_OP
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_FETCH_AND_OP = pmpix_fetch_and_op__
#pragma weak mpix_fetch_and_op__ = pmpix_fetch_and_op__
#pragma weak mpix_fetch_and_op_ = pmpix_fetch_and_op__
#pragma weak mpix_fetch_and_op = pmpix_fetch_and_op__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_FETCH_AND_OP = pmpix_fetch_and_op_
#pragma weak mpix_fetch_and_op__ = pmpix_fetch_and_op_
#pragma weak mpix_fetch_and_op_ = pmpix_fetch_and_op_
#pragma weak mpix_fetch_and_op = pmpix_fetch_and_op_
#else
#pragma weak MPIX_FETCH_AND_OP = pmpix_fetch_and_op
#pragma weak mpix_fetch_and_op__ = pmpix_fetch_and_op
#pragma weak mpix_fetch_and_op_ = pmpix_fetch_and_op
#pragma weak mpix_fetch_and_op = pmpix_fetch_and_op
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_FETCH_AND_OP( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPIX_FETCH_AND_OP = PMPIX_FETCH_AND_OP
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_fetch_and_op__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_fetch_and_op__ = pmpix_fetch_and_op__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_fetch_and_op( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_fetch_and_op = pmpix_fetch_and_op
#else
extern FORT_DLL_SPEC void FORT_CALL mpix_fetch_and_op_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_fetch_and_op_ = pmpix_fetch_and_op_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPIX_FETCH_AND_OP  MPIX_FETCH_AND_OP
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpix_fetch_and_op__  mpix_fetch_and_op__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpix_fetch_and_op  mpix_fetch_and_op
#else
#pragma _HP_SECONDARY_DEF pmpix_fetch_and_op_  mpix_fetch_and_op_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPIX_FETCH_AND_OP as PMPIX_FETCH_AND_OP
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpix_fetch_and_op__ as pmpix_fetch_and_op__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpix_fetch_and_op as pmpix_fetch_and_op
#else
#pragma _CRI duplicate mpix_fetch_and_op_ as pmpix_fetch_and_op_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPIX_FETCH_AND_OP( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_fetch_and_op__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_fetch_and_op( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_fetch_and_op_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpix_fetch_and_op__ = MPIX_FETCH_AND_OP
#pragma weak mpix_fetch_and_op_ = MPIX_FETCH_AND_OP
#pragma weak mpix_fetch_and_op = MPIX_FETCH_AND_OP
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_FETCH_AND_OP = mpix_fetch_and_op__
#pragma weak mpix_fetch_and_op_ = mpix_fetch_and_op__
#pragma weak mpix_fetch_and_op = mpix_fetch_and_op__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_FETCH_AND_OP = mpix_fetch_and_op_
#pragma weak mpix_fetch_and_op__ = mpix_fetch_and_op_
#pragma weak mpix_fetch_and_op = mpix_fetch_and_op_
#else
#pragma weak MPIX_FETCH_AND_OP = mpix_fetch_and_op
#pragma weak mpix_fetch_and_op__ = mpix_fetch_and_op
#pragma weak mpix_fetch_and_op_ = mpix_fetch_and_op
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPIX_FETCH_AND_OP( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_fetch_and_op__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_fetch_and_op_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpix_fetch_and_op( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpix_fetch_and_op__ = PMPIX_FETCH_AND_OP
#pragma weak pmpix_fetch_and_op_ = PMPIX_FETCH_AND_OP
#pragma weak pmpix_fetch_and_op = PMPIX_FETCH_AND_OP
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPIX_FETCH_AND_OP = pmpix_fetch_and_op__
#pragma weak pmpix_fetch_and_op_ = pmpix_fetch_and_op__
#pragma weak pmpix_fetch_and_op = pmpix_fetch_and_op__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPIX_FETCH_AND_OP = pmpix_fetch_and_op_
#pragma weak pmpix_fetch_and_op__ = pmpix_fetch_and_op_
#pragma weak pmpix_fetch_and_op = pmpix_fetch_and_op_
#else
#pragma weak PMPIX_FETCH_AND_OP = pmpix_fetch_and_op
#pragma weak pmpix_fetch_and_op__ = pmpix_fetch_and_op
#pragma weak pmpix_fetch_and_op_ = pmpix_fetch_and_op
#endif /* Test on name mapping */
#endif /* Use multiple pragma weak */

#ifdef F77_NAME_UPPER
#define mpix_fetch_and_op_ PMPIX_FETCH_AND_OP
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_fetch_and_op_ pmpix_fetch_and_op__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_fetch_and_op_ pmpix_fetch_and_op
#else
#define mpix_fetch_and_op_ pmpix_fetch_and_op_
#endif /* Test on name mapping */

/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPIX_Fetch_and_op
#define MPIX_Fetch_and_op PMPIX_Fetch_and_op 

#else

#ifdef F77_NAME_UPPER
#define mpix_fetch_and_op_ MPIX_FETCH_AND_OP
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_fetch_and_op_ mpix_fetch_and_op__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_fetch_and_op_ mpix_fetch_and_op
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpix_fetch_and_op_ ( void*v1, void*v2, MPI_Fint *v3, MPI_Fint *v4, MPI_Fint *v5, MPI_Fint *v6, MPI_Fint *v7, MPI_Fint *ierr ){
    *ierr = MPIX_Fetch_and_op( v1, v2, (MPI_Datatype)(*v3), *v4, *v5, *v6, *v7 );
}
