/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_GET_ACCUMULATE( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_get_accumulate__( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_get_accumulate( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_get_accumulate_( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPIX_GET_ACCUMULATE = PMPIX_GET_ACCUMULATE
#pragma weak mpix_get_accumulate__ = PMPIX_GET_ACCUMULATE
#pragma weak mpix_get_accumulate_ = PMPIX_GET_ACCUMULATE
#pragma weak mpix_get_accumulate = PMPIX_GET_ACCUMULATE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_GET_ACCUMULATE = pmpix_get_accumulate__
#pragma weak mpix_get_accumulate__ = pmpix_get_accumulate__
#pragma weak mpix_get_accumulate_ = pmpix_get_accumulate__
#pragma weak mpix_get_accumulate = pmpix_get_accumulate__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_GET_ACCUMULATE = pmpix_get_accumulate_
#pragma weak mpix_get_accumulate__ = pmpix_get_accumulate_
#pragma weak mpix_get_accumulate_ = pmpix_get_accumulate_
#pragma weak mpix_get_accumulate = pmpix_get_accumulate_
#else
#pragma weak MPIX_GET_ACCUMULATE = pmpix_get_accumulate
#pragma weak mpix_get_accumulate__ = pmpix_get_accumulate
#pragma weak mpix_get_accumulate_ = pmpix_get_accumulate
#pragma weak mpix_get_accumulate = pmpix_get_accumulate
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_GET_ACCUMULATE( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPIX_GET_ACCUMULATE = PMPIX_GET_ACCUMULATE
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_get_accumulate__( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_get_accumulate__ = pmpix_get_accumulate__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_get_accumulate( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_get_accumulate = pmpix_get_accumulate
#else
extern FORT_DLL_SPEC void FORT_CALL mpix_get_accumulate_( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_get_accumulate_ = pmpix_get_accumulate_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPIX_GET_ACCUMULATE  MPIX_GET_ACCUMULATE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpix_get_accumulate__  mpix_get_accumulate__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpix_get_accumulate  mpix_get_accumulate
#else
#pragma _HP_SECONDARY_DEF pmpix_get_accumulate_  mpix_get_accumulate_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPIX_GET_ACCUMULATE as PMPIX_GET_ACCUMULATE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpix_get_accumulate__ as pmpix_get_accumulate__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpix_get_accumulate as pmpix_get_accumulate
#else
#pragma _CRI duplicate mpix_get_accumulate_ as pmpix_get_accumulate_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPIX_GET_ACCUMULATE( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_get_accumulate__( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_get_accumulate( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_get_accumulate_( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpix_get_accumulate__ = MPIX_GET_ACCUMULATE
#pragma weak mpix_get_accumulate_ = MPIX_GET_ACCUMULATE
#pragma weak mpix_get_accumulate = MPIX_GET_ACCUMULATE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_GET_ACCUMULATE = mpix_get_accumulate__
#pragma weak mpix_get_accumulate_ = mpix_get_accumulate__
#pragma weak mpix_get_accumulate = mpix_get_accumulate__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_GET_ACCUMULATE = mpix_get_accumulate_
#pragma weak mpix_get_accumulate__ = mpix_get_accumulate_
#pragma weak mpix_get_accumulate = mpix_get_accumulate_
#else
#pragma weak MPIX_GET_ACCUMULATE = mpix_get_accumulate
#pragma weak mpix_get_accumulate__ = mpix_get_accumulate
#pragma weak mpix_get_accumulate_ = mpix_get_accumulate
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPIX_GET_ACCUMULATE( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_get_accumulate__( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_get_accumulate_( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpix_get_accumulate( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpix_get_accumulate__ = PMPIX_GET_ACCUMULATE
#pragma weak pmpix_get_accumulate_ = PMPIX_GET_ACCUMULATE
#pragma weak pmpix_get_accumulate = PMPIX_GET_ACCUMULATE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPIX_GET_ACCUMULATE = pmpix_get_accumulate__
#pragma weak pmpix_get_accumulate_ = pmpix_get_accumulate__
#pragma weak pmpix_get_accumulate = pmpix_get_accumulate__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPIX_GET_ACCUMULATE = pmpix_get_accumulate_
#pragma weak pmpix_get_accumulate__ = pmpix_get_accumulate_
#pragma weak pmpix_get_accumulate = pmpix_get_accumulate_
#else
#pragma weak PMPIX_GET_ACCUMULATE = pmpix_get_accumulate
#pragma weak pmpix_get_accumulate__ = pmpix_get_accumulate
#pragma weak pmpix_get_accumulate_ = pmpix_get_accumulate
#endif /* Test on name mapping */
#endif /* Use multiple pragma weak */

#ifdef F77_NAME_UPPER
#define mpix_get_accumulate_ PMPIX_GET_ACCUMULATE
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_get_accumulate_ pmpix_get_accumulate__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_get_accumulate_ pmpix_get_accumulate
#else
#define mpix_get_accumulate_ pmpix_get_accumulate_
#endif /* Test on name mapping */

/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPIX_Get_accumulate
#define MPIX_Get_accumulate PMPIX_Get_accumulate 

#else

#ifdef F77_NAME_UPPER
#define mpix_get_accumulate_ MPIX_GET_ACCUMULATE
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_get_accumulate_ mpix_get_accumulate__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_get_accumulate_ mpix_get_accumulate
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpix_get_accumulate_ ( void*v1, MPI_Fint *v2, MPI_Fint *v3, void*v4, MPI_Fint *v5, MPI_Fint *v6, MPI_Fint *v7, MPI_Fint *v8, MPI_Fint *v9, MPI_Fint *v10, MPI_Fint *v11, MPI_Fint *v12, MPI_Fint *ierr ){
    *ierr = MPIX_Get_accumulate( v1, *v2, (MPI_Datatype)(*v3), v4, *v5, (MPI_Datatype)(*v6), *v7, *v8, *v9, (MPI_Datatype)(*v10), *v11, *v12 );
}
