/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IALLGATHERV( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iallgatherv__( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iallgatherv( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iallgatherv_( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPIX_IALLGATHERV = PMPIX_IALLGATHERV
#pragma weak mpix_iallgatherv__ = PMPIX_IALLGATHERV
#pragma weak mpix_iallgatherv_ = PMPIX_IALLGATHERV
#pragma weak mpix_iallgatherv = PMPIX_IALLGATHERV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_IALLGATHERV = pmpix_iallgatherv__
#pragma weak mpix_iallgatherv__ = pmpix_iallgatherv__
#pragma weak mpix_iallgatherv_ = pmpix_iallgatherv__
#pragma weak mpix_iallgatherv = pmpix_iallgatherv__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_IALLGATHERV = pmpix_iallgatherv_
#pragma weak mpix_iallgatherv__ = pmpix_iallgatherv_
#pragma weak mpix_iallgatherv_ = pmpix_iallgatherv_
#pragma weak mpix_iallgatherv = pmpix_iallgatherv_
#else
#pragma weak MPIX_IALLGATHERV = pmpix_iallgatherv
#pragma weak mpix_iallgatherv__ = pmpix_iallgatherv
#pragma weak mpix_iallgatherv_ = pmpix_iallgatherv
#pragma weak mpix_iallgatherv = pmpix_iallgatherv
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IALLGATHERV( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPIX_IALLGATHERV = PMPIX_IALLGATHERV
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_iallgatherv__( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_iallgatherv__ = pmpix_iallgatherv__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_iallgatherv( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_iallgatherv = pmpix_iallgatherv
#else
extern FORT_DLL_SPEC void FORT_CALL mpix_iallgatherv_( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_iallgatherv_ = pmpix_iallgatherv_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPIX_IALLGATHERV  MPIX_IALLGATHERV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpix_iallgatherv__  mpix_iallgatherv__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpix_iallgatherv  mpix_iallgatherv
#else
#pragma _HP_SECONDARY_DEF pmpix_iallgatherv_  mpix_iallgatherv_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPIX_IALLGATHERV as PMPIX_IALLGATHERV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpix_iallgatherv__ as pmpix_iallgatherv__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpix_iallgatherv as pmpix_iallgatherv
#else
#pragma _CRI duplicate mpix_iallgatherv_ as pmpix_iallgatherv_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IALLGATHERV( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iallgatherv__( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iallgatherv( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iallgatherv_( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpix_iallgatherv__ = MPIX_IALLGATHERV
#pragma weak mpix_iallgatherv_ = MPIX_IALLGATHERV
#pragma weak mpix_iallgatherv = MPIX_IALLGATHERV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_IALLGATHERV = mpix_iallgatherv__
#pragma weak mpix_iallgatherv_ = mpix_iallgatherv__
#pragma weak mpix_iallgatherv = mpix_iallgatherv__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_IALLGATHERV = mpix_iallgatherv_
#pragma weak mpix_iallgatherv__ = mpix_iallgatherv_
#pragma weak mpix_iallgatherv = mpix_iallgatherv_
#else
#pragma weak MPIX_IALLGATHERV = mpix_iallgatherv
#pragma weak mpix_iallgatherv__ = mpix_iallgatherv
#pragma weak mpix_iallgatherv_ = mpix_iallgatherv
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPIX_IALLGATHERV( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_iallgatherv__( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_iallgatherv_( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpix_iallgatherv( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpix_iallgatherv__ = PMPIX_IALLGATHERV
#pragma weak pmpix_iallgatherv_ = PMPIX_IALLGATHERV
#pragma weak pmpix_iallgatherv = PMPIX_IALLGATHERV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPIX_IALLGATHERV = pmpix_iallgatherv__
#pragma weak pmpix_iallgatherv_ = pmpix_iallgatherv__
#pragma weak pmpix_iallgatherv = pmpix_iallgatherv__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPIX_IALLGATHERV = pmpix_iallgatherv_
#pragma weak pmpix_iallgatherv__ = pmpix_iallgatherv_
#pragma weak pmpix_iallgatherv = pmpix_iallgatherv_
#else
#pragma weak PMPIX_IALLGATHERV = pmpix_iallgatherv
#pragma weak pmpix_iallgatherv__ = pmpix_iallgatherv
#pragma weak pmpix_iallgatherv_ = pmpix_iallgatherv
#endif /* Test on name mapping */
#endif /* Use multiple pragma weak */

#ifdef F77_NAME_UPPER
#define mpix_iallgatherv_ PMPIX_IALLGATHERV
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_iallgatherv_ pmpix_iallgatherv__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_iallgatherv_ pmpix_iallgatherv
#else
#define mpix_iallgatherv_ pmpix_iallgatherv_
#endif /* Test on name mapping */

/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPIX_Iallgatherv
#define MPIX_Iallgatherv PMPIX_Iallgatherv 

#else

#ifdef F77_NAME_UPPER
#define mpix_iallgatherv_ MPIX_IALLGATHERV
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_iallgatherv_ mpix_iallgatherv__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_iallgatherv_ mpix_iallgatherv
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpix_iallgatherv_ ( void*v1, MPI_Fint *v2, MPI_Fint *v3, void*v4, MPI_Fint *v5, MPI_Fint *v6, MPI_Fint *v7, MPI_Fint *v8, MPI_Fint *v9, MPI_Fint *ierr ){

#ifndef HAVE_MPI_F_INIT_WORKS_WITH_C
    if (MPIR_F_NeedInit){ mpirinitf_(); MPIR_F_NeedInit = 0; }
#endif
    if (v1 == MPIR_F_MPI_IN_PLACE) v1 = MPI_IN_PLACE;
    *ierr = MPIX_Iallgatherv( v1, *v2, (MPI_Datatype)(*v3), v4, v5, v6, (MPI_Datatype)(*v7), (MPI_Comm)(*v8), (MPI_Request *)(v9) );
}
