/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IALLTOALLW( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ialltoallw__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ialltoallw( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ialltoallw_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPIX_IALLTOALLW = PMPIX_IALLTOALLW
#pragma weak mpix_ialltoallw__ = PMPIX_IALLTOALLW
#pragma weak mpix_ialltoallw_ = PMPIX_IALLTOALLW
#pragma weak mpix_ialltoallw = PMPIX_IALLTOALLW
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_IALLTOALLW = pmpix_ialltoallw__
#pragma weak mpix_ialltoallw__ = pmpix_ialltoallw__
#pragma weak mpix_ialltoallw_ = pmpix_ialltoallw__
#pragma weak mpix_ialltoallw = pmpix_ialltoallw__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_IALLTOALLW = pmpix_ialltoallw_
#pragma weak mpix_ialltoallw__ = pmpix_ialltoallw_
#pragma weak mpix_ialltoallw_ = pmpix_ialltoallw_
#pragma weak mpix_ialltoallw = pmpix_ialltoallw_
#else
#pragma weak MPIX_IALLTOALLW = pmpix_ialltoallw
#pragma weak mpix_ialltoallw__ = pmpix_ialltoallw
#pragma weak mpix_ialltoallw_ = pmpix_ialltoallw
#pragma weak mpix_ialltoallw = pmpix_ialltoallw
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IALLTOALLW( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPIX_IALLTOALLW = PMPIX_IALLTOALLW
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_ialltoallw__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_ialltoallw__ = pmpix_ialltoallw__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_ialltoallw( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_ialltoallw = pmpix_ialltoallw
#else
extern FORT_DLL_SPEC void FORT_CALL mpix_ialltoallw_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_ialltoallw_ = pmpix_ialltoallw_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPIX_IALLTOALLW  MPIX_IALLTOALLW
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpix_ialltoallw__  mpix_ialltoallw__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpix_ialltoallw  mpix_ialltoallw
#else
#pragma _HP_SECONDARY_DEF pmpix_ialltoallw_  mpix_ialltoallw_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPIX_IALLTOALLW as PMPIX_IALLTOALLW
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpix_ialltoallw__ as pmpix_ialltoallw__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpix_ialltoallw as pmpix_ialltoallw
#else
#pragma _CRI duplicate mpix_ialltoallw_ as pmpix_ialltoallw_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IALLTOALLW( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ialltoallw__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ialltoallw( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ialltoallw_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpix_ialltoallw__ = MPIX_IALLTOALLW
#pragma weak mpix_ialltoallw_ = MPIX_IALLTOALLW
#pragma weak mpix_ialltoallw = MPIX_IALLTOALLW
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_IALLTOALLW = mpix_ialltoallw__
#pragma weak mpix_ialltoallw_ = mpix_ialltoallw__
#pragma weak mpix_ialltoallw = mpix_ialltoallw__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_IALLTOALLW = mpix_ialltoallw_
#pragma weak mpix_ialltoallw__ = mpix_ialltoallw_
#pragma weak mpix_ialltoallw = mpix_ialltoallw_
#else
#pragma weak MPIX_IALLTOALLW = mpix_ialltoallw
#pragma weak mpix_ialltoallw__ = mpix_ialltoallw
#pragma weak mpix_ialltoallw_ = mpix_ialltoallw
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPIX_IALLTOALLW( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_ialltoallw__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_ialltoallw_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpix_ialltoallw( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpix_ialltoallw__ = PMPIX_IALLTOALLW
#pragma weak pmpix_ialltoallw_ = PMPIX_IALLTOALLW
#pragma weak pmpix_ialltoallw = PMPIX_IALLTOALLW
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPIX_IALLTOALLW = pmpix_ialltoallw__
#pragma weak pmpix_ialltoallw_ = pmpix_ialltoallw__
#pragma weak pmpix_ialltoallw = pmpix_ialltoallw__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPIX_IALLTOALLW = pmpix_ialltoallw_
#pragma weak pmpix_ialltoallw__ = pmpix_ialltoallw_
#pragma weak pmpix_ialltoallw = pmpix_ialltoallw_
#else
#pragma weak PMPIX_IALLTOALLW = pmpix_ialltoallw
#pragma weak pmpix_ialltoallw__ = pmpix_ialltoallw
#pragma weak pmpix_ialltoallw_ = pmpix_ialltoallw
#endif /* Test on name mapping */
#endif /* Use multiple pragma weak */

#ifdef F77_NAME_UPPER
#define mpix_ialltoallw_ PMPIX_IALLTOALLW
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_ialltoallw_ pmpix_ialltoallw__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_ialltoallw_ pmpix_ialltoallw
#else
#define mpix_ialltoallw_ pmpix_ialltoallw_
#endif /* Test on name mapping */

/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPIX_Ialltoallw
#define MPIX_Ialltoallw PMPIX_Ialltoallw 

#else

#ifdef F77_NAME_UPPER
#define mpix_ialltoallw_ MPIX_IALLTOALLW
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_ialltoallw_ mpix_ialltoallw__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_ialltoallw_ mpix_ialltoallw
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpix_ialltoallw_ ( void*v1, MPI_Fint *v2, MPI_Fint *v3, MPI_Fint *v4, void*v5, MPI_Fint *v6, MPI_Fint *v7, MPI_Fint *v8, MPI_Fint *v9, MPI_Fint *v10, MPI_Fint *ierr ){

#ifndef HAVE_MPI_F_INIT_WORKS_WITH_C
    if (MPIR_F_NeedInit){ mpirinitf_(); MPIR_F_NeedInit = 0; }
#endif
    if (v1 == MPIR_F_MPI_IN_PLACE) v1 = MPI_IN_PLACE;
    *ierr = MPIX_Ialltoallw( v1, v2, v3, (MPI_Datatype *)(v4), v5, v6, v7, (MPI_Datatype *)(v8), (MPI_Comm)(*v9), (MPI_Request *)(v10) );
}
