/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IALLGATHER( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iallgather__( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iallgather( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iallgather_( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPIX_IALLGATHER = PMPIX_IALLGATHER
#pragma weak mpix_iallgather__ = PMPIX_IALLGATHER
#pragma weak mpix_iallgather_ = PMPIX_IALLGATHER
#pragma weak mpix_iallgather = PMPIX_IALLGATHER
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_IALLGATHER = pmpix_iallgather__
#pragma weak mpix_iallgather__ = pmpix_iallgather__
#pragma weak mpix_iallgather_ = pmpix_iallgather__
#pragma weak mpix_iallgather = pmpix_iallgather__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_IALLGATHER = pmpix_iallgather_
#pragma weak mpix_iallgather__ = pmpix_iallgather_
#pragma weak mpix_iallgather_ = pmpix_iallgather_
#pragma weak mpix_iallgather = pmpix_iallgather_
#else
#pragma weak MPIX_IALLGATHER = pmpix_iallgather
#pragma weak mpix_iallgather__ = pmpix_iallgather
#pragma weak mpix_iallgather_ = pmpix_iallgather
#pragma weak mpix_iallgather = pmpix_iallgather
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IALLGATHER( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPIX_IALLGATHER = PMPIX_IALLGATHER
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_iallgather__( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_iallgather__ = pmpix_iallgather__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_iallgather( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_iallgather = pmpix_iallgather
#else
extern FORT_DLL_SPEC void FORT_CALL mpix_iallgather_( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_iallgather_ = pmpix_iallgather_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPIX_IALLGATHER  MPIX_IALLGATHER
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpix_iallgather__  mpix_iallgather__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpix_iallgather  mpix_iallgather
#else
#pragma _HP_SECONDARY_DEF pmpix_iallgather_  mpix_iallgather_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPIX_IALLGATHER as PMPIX_IALLGATHER
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpix_iallgather__ as pmpix_iallgather__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpix_iallgather as pmpix_iallgather
#else
#pragma _CRI duplicate mpix_iallgather_ as pmpix_iallgather_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IALLGATHER( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iallgather__( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iallgather( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iallgather_( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpix_iallgather__ = MPIX_IALLGATHER
#pragma weak mpix_iallgather_ = MPIX_IALLGATHER
#pragma weak mpix_iallgather = MPIX_IALLGATHER
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_IALLGATHER = mpix_iallgather__
#pragma weak mpix_iallgather_ = mpix_iallgather__
#pragma weak mpix_iallgather = mpix_iallgather__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_IALLGATHER = mpix_iallgather_
#pragma weak mpix_iallgather__ = mpix_iallgather_
#pragma weak mpix_iallgather = mpix_iallgather_
#else
#pragma weak MPIX_IALLGATHER = mpix_iallgather
#pragma weak mpix_iallgather__ = mpix_iallgather
#pragma weak mpix_iallgather_ = mpix_iallgather
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPIX_IALLGATHER( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_iallgather__( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_iallgather_( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpix_iallgather( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpix_iallgather__ = PMPIX_IALLGATHER
#pragma weak pmpix_iallgather_ = PMPIX_IALLGATHER
#pragma weak pmpix_iallgather = PMPIX_IALLGATHER
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPIX_IALLGATHER = pmpix_iallgather__
#pragma weak pmpix_iallgather_ = pmpix_iallgather__
#pragma weak pmpix_iallgather = pmpix_iallgather__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPIX_IALLGATHER = pmpix_iallgather_
#pragma weak pmpix_iallgather__ = pmpix_iallgather_
#pragma weak pmpix_iallgather = pmpix_iallgather_
#else
#pragma weak PMPIX_IALLGATHER = pmpix_iallgather
#pragma weak pmpix_iallgather__ = pmpix_iallgather
#pragma weak pmpix_iallgather_ = pmpix_iallgather
#endif /* Test on name mapping */
#endif /* Use multiple pragma weak */

#ifdef F77_NAME_UPPER
#define mpix_iallgather_ PMPIX_IALLGATHER
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_iallgather_ pmpix_iallgather__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_iallgather_ pmpix_iallgather
#else
#define mpix_iallgather_ pmpix_iallgather_
#endif /* Test on name mapping */

/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPIX_Iallgather
#define MPIX_Iallgather PMPIX_Iallgather 

#else

#ifdef F77_NAME_UPPER
#define mpix_iallgather_ MPIX_IALLGATHER
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_iallgather_ mpix_iallgather__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_iallgather_ mpix_iallgather
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpix_iallgather_ ( void*v1, MPI_Fint *v2, MPI_Fint *v3, void*v4, MPI_Fint *v5, MPI_Fint *v6, MPI_Fint *v7, MPI_Fint *v8, MPI_Fint *ierr ){

#ifndef HAVE_MPI_F_INIT_WORKS_WITH_C
    if (MPIR_F_NeedInit){ mpirinitf_(); MPIR_F_NeedInit = 0; }
#endif
    if (v1 == MPIR_F_MPI_IN_PLACE) v1 = MPI_IN_PLACE;
    *ierr = MPIX_Iallgather( v1, *v2, (MPI_Datatype)(*v3), v4, *v5, (MPI_Datatype)(*v6), (MPI_Comm)(*v7), (MPI_Request *)(v8) );
}
