/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IALLTOALLV( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ialltoallv__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ialltoallv( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ialltoallv_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPIX_IALLTOALLV = PMPIX_IALLTOALLV
#pragma weak mpix_ialltoallv__ = PMPIX_IALLTOALLV
#pragma weak mpix_ialltoallv_ = PMPIX_IALLTOALLV
#pragma weak mpix_ialltoallv = PMPIX_IALLTOALLV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_IALLTOALLV = pmpix_ialltoallv__
#pragma weak mpix_ialltoallv__ = pmpix_ialltoallv__
#pragma weak mpix_ialltoallv_ = pmpix_ialltoallv__
#pragma weak mpix_ialltoallv = pmpix_ialltoallv__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_IALLTOALLV = pmpix_ialltoallv_
#pragma weak mpix_ialltoallv__ = pmpix_ialltoallv_
#pragma weak mpix_ialltoallv_ = pmpix_ialltoallv_
#pragma weak mpix_ialltoallv = pmpix_ialltoallv_
#else
#pragma weak MPIX_IALLTOALLV = pmpix_ialltoallv
#pragma weak mpix_ialltoallv__ = pmpix_ialltoallv
#pragma weak mpix_ialltoallv_ = pmpix_ialltoallv
#pragma weak mpix_ialltoallv = pmpix_ialltoallv
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IALLTOALLV( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPIX_IALLTOALLV = PMPIX_IALLTOALLV
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_ialltoallv__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_ialltoallv__ = pmpix_ialltoallv__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_ialltoallv( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_ialltoallv = pmpix_ialltoallv
#else
extern FORT_DLL_SPEC void FORT_CALL mpix_ialltoallv_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_ialltoallv_ = pmpix_ialltoallv_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPIX_IALLTOALLV  MPIX_IALLTOALLV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpix_ialltoallv__  mpix_ialltoallv__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpix_ialltoallv  mpix_ialltoallv
#else
#pragma _HP_SECONDARY_DEF pmpix_ialltoallv_  mpix_ialltoallv_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPIX_IALLTOALLV as PMPIX_IALLTOALLV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpix_ialltoallv__ as pmpix_ialltoallv__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpix_ialltoallv as pmpix_ialltoallv
#else
#pragma _CRI duplicate mpix_ialltoallv_ as pmpix_ialltoallv_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IALLTOALLV( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ialltoallv__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ialltoallv( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ialltoallv_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpix_ialltoallv__ = MPIX_IALLTOALLV
#pragma weak mpix_ialltoallv_ = MPIX_IALLTOALLV
#pragma weak mpix_ialltoallv = MPIX_IALLTOALLV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_IALLTOALLV = mpix_ialltoallv__
#pragma weak mpix_ialltoallv_ = mpix_ialltoallv__
#pragma weak mpix_ialltoallv = mpix_ialltoallv__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_IALLTOALLV = mpix_ialltoallv_
#pragma weak mpix_ialltoallv__ = mpix_ialltoallv_
#pragma weak mpix_ialltoallv = mpix_ialltoallv_
#else
#pragma weak MPIX_IALLTOALLV = mpix_ialltoallv
#pragma weak mpix_ialltoallv__ = mpix_ialltoallv
#pragma weak mpix_ialltoallv_ = mpix_ialltoallv
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPIX_IALLTOALLV( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_ialltoallv__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_ialltoallv_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpix_ialltoallv( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpix_ialltoallv__ = PMPIX_IALLTOALLV
#pragma weak pmpix_ialltoallv_ = PMPIX_IALLTOALLV
#pragma weak pmpix_ialltoallv = PMPIX_IALLTOALLV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPIX_IALLTOALLV = pmpix_ialltoallv__
#pragma weak pmpix_ialltoallv_ = pmpix_ialltoallv__
#pragma weak pmpix_ialltoallv = pmpix_ialltoallv__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPIX_IALLTOALLV = pmpix_ialltoallv_
#pragma weak pmpix_ialltoallv__ = pmpix_ialltoallv_
#pragma weak pmpix_ialltoallv = pmpix_ialltoallv_
#else
#pragma weak PMPIX_IALLTOALLV = pmpix_ialltoallv
#pragma weak pmpix_ialltoallv__ = pmpix_ialltoallv
#pragma weak pmpix_ialltoallv_ = pmpix_ialltoallv
#endif /* Test on name mapping */
#endif /* Use multiple pragma weak */

#ifdef F77_NAME_UPPER
#define mpix_ialltoallv_ PMPIX_IALLTOALLV
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_ialltoallv_ pmpix_ialltoallv__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_ialltoallv_ pmpix_ialltoallv
#else
#define mpix_ialltoallv_ pmpix_ialltoallv_
#endif /* Test on name mapping */

/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPIX_Ialltoallv
#define MPIX_Ialltoallv PMPIX_Ialltoallv 

#else

#ifdef F77_NAME_UPPER
#define mpix_ialltoallv_ MPIX_IALLTOALLV
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_ialltoallv_ mpix_ialltoallv__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_ialltoallv_ mpix_ialltoallv
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpix_ialltoallv_ ( void*v1, MPI_Fint *v2, MPI_Fint *v3, MPI_Fint *v4, void*v5, MPI_Fint *v6, MPI_Fint *v7, MPI_Fint *v8, MPI_Fint *v9, MPI_Fint *v10, MPI_Fint *ierr ){

#ifndef HAVE_MPI_F_INIT_WORKS_WITH_C
    if (MPIR_F_NeedInit){ mpirinitf_(); MPIR_F_NeedInit = 0; }
#endif
    if (v1 == MPIR_F_MPI_IN_PLACE) v1 = MPI_IN_PLACE;
    *ierr = MPIX_Ialltoallv( v1, v2, v3, (MPI_Datatype)(*v4), v5, v6, v7, (MPI_Datatype)(*v8), (MPI_Comm)(*v9), (MPI_Request *)(v10) );
}
