/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IBARRIER( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ibarrier__( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ibarrier( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ibarrier_( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPIX_IBARRIER = PMPIX_IBARRIER
#pragma weak mpix_ibarrier__ = PMPIX_IBARRIER
#pragma weak mpix_ibarrier_ = PMPIX_IBARRIER
#pragma weak mpix_ibarrier = PMPIX_IBARRIER
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_IBARRIER = pmpix_ibarrier__
#pragma weak mpix_ibarrier__ = pmpix_ibarrier__
#pragma weak mpix_ibarrier_ = pmpix_ibarrier__
#pragma weak mpix_ibarrier = pmpix_ibarrier__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_IBARRIER = pmpix_ibarrier_
#pragma weak mpix_ibarrier__ = pmpix_ibarrier_
#pragma weak mpix_ibarrier_ = pmpix_ibarrier_
#pragma weak mpix_ibarrier = pmpix_ibarrier_
#else
#pragma weak MPIX_IBARRIER = pmpix_ibarrier
#pragma weak mpix_ibarrier__ = pmpix_ibarrier
#pragma weak mpix_ibarrier_ = pmpix_ibarrier
#pragma weak mpix_ibarrier = pmpix_ibarrier
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IBARRIER( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPIX_IBARRIER = PMPIX_IBARRIER
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_ibarrier__( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_ibarrier__ = pmpix_ibarrier__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_ibarrier( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_ibarrier = pmpix_ibarrier
#else
extern FORT_DLL_SPEC void FORT_CALL mpix_ibarrier_( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_ibarrier_ = pmpix_ibarrier_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPIX_IBARRIER  MPIX_IBARRIER
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpix_ibarrier__  mpix_ibarrier__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpix_ibarrier  mpix_ibarrier
#else
#pragma _HP_SECONDARY_DEF pmpix_ibarrier_  mpix_ibarrier_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPIX_IBARRIER as PMPIX_IBARRIER
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpix_ibarrier__ as pmpix_ibarrier__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpix_ibarrier as pmpix_ibarrier
#else
#pragma _CRI duplicate mpix_ibarrier_ as pmpix_ibarrier_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IBARRIER( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ibarrier__( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ibarrier( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ibarrier_( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpix_ibarrier__ = MPIX_IBARRIER
#pragma weak mpix_ibarrier_ = MPIX_IBARRIER
#pragma weak mpix_ibarrier = MPIX_IBARRIER
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_IBARRIER = mpix_ibarrier__
#pragma weak mpix_ibarrier_ = mpix_ibarrier__
#pragma weak mpix_ibarrier = mpix_ibarrier__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_IBARRIER = mpix_ibarrier_
#pragma weak mpix_ibarrier__ = mpix_ibarrier_
#pragma weak mpix_ibarrier = mpix_ibarrier_
#else
#pragma weak MPIX_IBARRIER = mpix_ibarrier
#pragma weak mpix_ibarrier__ = mpix_ibarrier
#pragma weak mpix_ibarrier_ = mpix_ibarrier
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPIX_IBARRIER( MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_ibarrier__( MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_ibarrier_( MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpix_ibarrier( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpix_ibarrier__ = PMPIX_IBARRIER
#pragma weak pmpix_ibarrier_ = PMPIX_IBARRIER
#pragma weak pmpix_ibarrier = PMPIX_IBARRIER
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPIX_IBARRIER = pmpix_ibarrier__
#pragma weak pmpix_ibarrier_ = pmpix_ibarrier__
#pragma weak pmpix_ibarrier = pmpix_ibarrier__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPIX_IBARRIER = pmpix_ibarrier_
#pragma weak pmpix_ibarrier__ = pmpix_ibarrier_
#pragma weak pmpix_ibarrier = pmpix_ibarrier_
#else
#pragma weak PMPIX_IBARRIER = pmpix_ibarrier
#pragma weak pmpix_ibarrier__ = pmpix_ibarrier
#pragma weak pmpix_ibarrier_ = pmpix_ibarrier
#endif /* Test on name mapping */
#endif /* Use multiple pragma weak */

#ifdef F77_NAME_UPPER
#define mpix_ibarrier_ PMPIX_IBARRIER
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_ibarrier_ pmpix_ibarrier__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_ibarrier_ pmpix_ibarrier
#else
#define mpix_ibarrier_ pmpix_ibarrier_
#endif /* Test on name mapping */

/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPIX_Ibarrier
#define MPIX_Ibarrier PMPIX_Ibarrier 

#else

#ifdef F77_NAME_UPPER
#define mpix_ibarrier_ MPIX_IBARRIER
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_ibarrier_ mpix_ibarrier__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_ibarrier_ mpix_ibarrier
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpix_ibarrier_ ( MPI_Fint *v1, MPI_Fint *v2, MPI_Fint *ierr ){
    *ierr = MPIX_Ibarrier( (MPI_Comm)(*v1), (MPI_Request *)(v2) );
}
