/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IBCAST( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ibcast__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ibcast( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ibcast_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPIX_IBCAST = PMPIX_IBCAST
#pragma weak mpix_ibcast__ = PMPIX_IBCAST
#pragma weak mpix_ibcast_ = PMPIX_IBCAST
#pragma weak mpix_ibcast = PMPIX_IBCAST
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_IBCAST = pmpix_ibcast__
#pragma weak mpix_ibcast__ = pmpix_ibcast__
#pragma weak mpix_ibcast_ = pmpix_ibcast__
#pragma weak mpix_ibcast = pmpix_ibcast__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_IBCAST = pmpix_ibcast_
#pragma weak mpix_ibcast__ = pmpix_ibcast_
#pragma weak mpix_ibcast_ = pmpix_ibcast_
#pragma weak mpix_ibcast = pmpix_ibcast_
#else
#pragma weak MPIX_IBCAST = pmpix_ibcast
#pragma weak mpix_ibcast__ = pmpix_ibcast
#pragma weak mpix_ibcast_ = pmpix_ibcast
#pragma weak mpix_ibcast = pmpix_ibcast
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IBCAST( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPIX_IBCAST = PMPIX_IBCAST
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_ibcast__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_ibcast__ = pmpix_ibcast__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_ibcast( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_ibcast = pmpix_ibcast
#else
extern FORT_DLL_SPEC void FORT_CALL mpix_ibcast_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_ibcast_ = pmpix_ibcast_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPIX_IBCAST  MPIX_IBCAST
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpix_ibcast__  mpix_ibcast__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpix_ibcast  mpix_ibcast
#else
#pragma _HP_SECONDARY_DEF pmpix_ibcast_  mpix_ibcast_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPIX_IBCAST as PMPIX_IBCAST
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpix_ibcast__ as pmpix_ibcast__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpix_ibcast as pmpix_ibcast
#else
#pragma _CRI duplicate mpix_ibcast_ as pmpix_ibcast_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IBCAST( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ibcast__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ibcast( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ibcast_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpix_ibcast__ = MPIX_IBCAST
#pragma weak mpix_ibcast_ = MPIX_IBCAST
#pragma weak mpix_ibcast = MPIX_IBCAST
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_IBCAST = mpix_ibcast__
#pragma weak mpix_ibcast_ = mpix_ibcast__
#pragma weak mpix_ibcast = mpix_ibcast__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_IBCAST = mpix_ibcast_
#pragma weak mpix_ibcast__ = mpix_ibcast_
#pragma weak mpix_ibcast = mpix_ibcast_
#else
#pragma weak MPIX_IBCAST = mpix_ibcast
#pragma weak mpix_ibcast__ = mpix_ibcast
#pragma weak mpix_ibcast_ = mpix_ibcast
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPIX_IBCAST( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_ibcast__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_ibcast_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpix_ibcast( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpix_ibcast__ = PMPIX_IBCAST
#pragma weak pmpix_ibcast_ = PMPIX_IBCAST
#pragma weak pmpix_ibcast = PMPIX_IBCAST
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPIX_IBCAST = pmpix_ibcast__
#pragma weak pmpix_ibcast_ = pmpix_ibcast__
#pragma weak pmpix_ibcast = pmpix_ibcast__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPIX_IBCAST = pmpix_ibcast_
#pragma weak pmpix_ibcast__ = pmpix_ibcast_
#pragma weak pmpix_ibcast = pmpix_ibcast_
#else
#pragma weak PMPIX_IBCAST = pmpix_ibcast
#pragma weak pmpix_ibcast__ = pmpix_ibcast
#pragma weak pmpix_ibcast_ = pmpix_ibcast
#endif /* Test on name mapping */
#endif /* Use multiple pragma weak */

#ifdef F77_NAME_UPPER
#define mpix_ibcast_ PMPIX_IBCAST
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_ibcast_ pmpix_ibcast__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_ibcast_ pmpix_ibcast
#else
#define mpix_ibcast_ pmpix_ibcast_
#endif /* Test on name mapping */

/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPIX_Ibcast
#define MPIX_Ibcast PMPIX_Ibcast 

#else

#ifdef F77_NAME_UPPER
#define mpix_ibcast_ MPIX_IBCAST
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_ibcast_ mpix_ibcast__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_ibcast_ mpix_ibcast
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpix_ibcast_ ( void*v1, MPI_Fint *v2, MPI_Fint *v3, MPI_Fint *v4, MPI_Fint *v5, MPI_Fint *v6, MPI_Fint *ierr ){
    *ierr = MPIX_Ibcast( v1, *v2, (MPI_Datatype)(*v3), *v4, (MPI_Comm)(*v5), (MPI_Request *)(v6) );
}
