/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IEXSCAN( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iexscan__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iexscan( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iexscan_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPIX_IEXSCAN = PMPIX_IEXSCAN
#pragma weak mpix_iexscan__ = PMPIX_IEXSCAN
#pragma weak mpix_iexscan_ = PMPIX_IEXSCAN
#pragma weak mpix_iexscan = PMPIX_IEXSCAN
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_IEXSCAN = pmpix_iexscan__
#pragma weak mpix_iexscan__ = pmpix_iexscan__
#pragma weak mpix_iexscan_ = pmpix_iexscan__
#pragma weak mpix_iexscan = pmpix_iexscan__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_IEXSCAN = pmpix_iexscan_
#pragma weak mpix_iexscan__ = pmpix_iexscan_
#pragma weak mpix_iexscan_ = pmpix_iexscan_
#pragma weak mpix_iexscan = pmpix_iexscan_
#else
#pragma weak MPIX_IEXSCAN = pmpix_iexscan
#pragma weak mpix_iexscan__ = pmpix_iexscan
#pragma weak mpix_iexscan_ = pmpix_iexscan
#pragma weak mpix_iexscan = pmpix_iexscan
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IEXSCAN( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPIX_IEXSCAN = PMPIX_IEXSCAN
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_iexscan__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_iexscan__ = pmpix_iexscan__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_iexscan( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_iexscan = pmpix_iexscan
#else
extern FORT_DLL_SPEC void FORT_CALL mpix_iexscan_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_iexscan_ = pmpix_iexscan_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPIX_IEXSCAN  MPIX_IEXSCAN
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpix_iexscan__  mpix_iexscan__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpix_iexscan  mpix_iexscan
#else
#pragma _HP_SECONDARY_DEF pmpix_iexscan_  mpix_iexscan_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPIX_IEXSCAN as PMPIX_IEXSCAN
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpix_iexscan__ as pmpix_iexscan__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpix_iexscan as pmpix_iexscan
#else
#pragma _CRI duplicate mpix_iexscan_ as pmpix_iexscan_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IEXSCAN( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iexscan__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iexscan( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iexscan_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpix_iexscan__ = MPIX_IEXSCAN
#pragma weak mpix_iexscan_ = MPIX_IEXSCAN
#pragma weak mpix_iexscan = MPIX_IEXSCAN
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_IEXSCAN = mpix_iexscan__
#pragma weak mpix_iexscan_ = mpix_iexscan__
#pragma weak mpix_iexscan = mpix_iexscan__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_IEXSCAN = mpix_iexscan_
#pragma weak mpix_iexscan__ = mpix_iexscan_
#pragma weak mpix_iexscan = mpix_iexscan_
#else
#pragma weak MPIX_IEXSCAN = mpix_iexscan
#pragma weak mpix_iexscan__ = mpix_iexscan
#pragma weak mpix_iexscan_ = mpix_iexscan
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPIX_IEXSCAN( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_iexscan__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_iexscan_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpix_iexscan( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpix_iexscan__ = PMPIX_IEXSCAN
#pragma weak pmpix_iexscan_ = PMPIX_IEXSCAN
#pragma weak pmpix_iexscan = PMPIX_IEXSCAN
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPIX_IEXSCAN = pmpix_iexscan__
#pragma weak pmpix_iexscan_ = pmpix_iexscan__
#pragma weak pmpix_iexscan = pmpix_iexscan__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPIX_IEXSCAN = pmpix_iexscan_
#pragma weak pmpix_iexscan__ = pmpix_iexscan_
#pragma weak pmpix_iexscan = pmpix_iexscan_
#else
#pragma weak PMPIX_IEXSCAN = pmpix_iexscan
#pragma weak pmpix_iexscan__ = pmpix_iexscan
#pragma weak pmpix_iexscan_ = pmpix_iexscan
#endif /* Test on name mapping */
#endif /* Use multiple pragma weak */

#ifdef F77_NAME_UPPER
#define mpix_iexscan_ PMPIX_IEXSCAN
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_iexscan_ pmpix_iexscan__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_iexscan_ pmpix_iexscan
#else
#define mpix_iexscan_ pmpix_iexscan_
#endif /* Test on name mapping */

/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPIX_Iexscan
#define MPIX_Iexscan PMPIX_Iexscan 

#else

#ifdef F77_NAME_UPPER
#define mpix_iexscan_ MPIX_IEXSCAN
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_iexscan_ mpix_iexscan__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_iexscan_ mpix_iexscan
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpix_iexscan_ ( void*v1, void*v2, MPI_Fint *v3, MPI_Fint *v4, MPI_Fint *v5, MPI_Fint *v6, MPI_Fint *v7, MPI_Fint *ierr ){
    *ierr = MPIX_Iexscan( v1, v2, *v3, (MPI_Datatype)(*v4), *v5, (MPI_Comm)(*v6), (MPI_Request *)(v7) );
}
