/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IGATHERV( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_igatherv__( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_igatherv( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_igatherv_( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPIX_IGATHERV = PMPIX_IGATHERV
#pragma weak mpix_igatherv__ = PMPIX_IGATHERV
#pragma weak mpix_igatherv_ = PMPIX_IGATHERV
#pragma weak mpix_igatherv = PMPIX_IGATHERV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_IGATHERV = pmpix_igatherv__
#pragma weak mpix_igatherv__ = pmpix_igatherv__
#pragma weak mpix_igatherv_ = pmpix_igatherv__
#pragma weak mpix_igatherv = pmpix_igatherv__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_IGATHERV = pmpix_igatherv_
#pragma weak mpix_igatherv__ = pmpix_igatherv_
#pragma weak mpix_igatherv_ = pmpix_igatherv_
#pragma weak mpix_igatherv = pmpix_igatherv_
#else
#pragma weak MPIX_IGATHERV = pmpix_igatherv
#pragma weak mpix_igatherv__ = pmpix_igatherv
#pragma weak mpix_igatherv_ = pmpix_igatherv
#pragma weak mpix_igatherv = pmpix_igatherv
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IGATHERV( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPIX_IGATHERV = PMPIX_IGATHERV
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_igatherv__( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_igatherv__ = pmpix_igatherv__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_igatherv( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_igatherv = pmpix_igatherv
#else
extern FORT_DLL_SPEC void FORT_CALL mpix_igatherv_( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_igatherv_ = pmpix_igatherv_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPIX_IGATHERV  MPIX_IGATHERV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpix_igatherv__  mpix_igatherv__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpix_igatherv  mpix_igatherv
#else
#pragma _HP_SECONDARY_DEF pmpix_igatherv_  mpix_igatherv_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPIX_IGATHERV as PMPIX_IGATHERV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpix_igatherv__ as pmpix_igatherv__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpix_igatherv as pmpix_igatherv
#else
#pragma _CRI duplicate mpix_igatherv_ as pmpix_igatherv_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IGATHERV( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_igatherv__( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_igatherv( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_igatherv_( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpix_igatherv__ = MPIX_IGATHERV
#pragma weak mpix_igatherv_ = MPIX_IGATHERV
#pragma weak mpix_igatherv = MPIX_IGATHERV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_IGATHERV = mpix_igatherv__
#pragma weak mpix_igatherv_ = mpix_igatherv__
#pragma weak mpix_igatherv = mpix_igatherv__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_IGATHERV = mpix_igatherv_
#pragma weak mpix_igatherv__ = mpix_igatherv_
#pragma weak mpix_igatherv = mpix_igatherv_
#else
#pragma weak MPIX_IGATHERV = mpix_igatherv
#pragma weak mpix_igatherv__ = mpix_igatherv
#pragma weak mpix_igatherv_ = mpix_igatherv
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPIX_IGATHERV( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_igatherv__( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_igatherv_( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpix_igatherv( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpix_igatherv__ = PMPIX_IGATHERV
#pragma weak pmpix_igatherv_ = PMPIX_IGATHERV
#pragma weak pmpix_igatherv = PMPIX_IGATHERV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPIX_IGATHERV = pmpix_igatherv__
#pragma weak pmpix_igatherv_ = pmpix_igatherv__
#pragma weak pmpix_igatherv = pmpix_igatherv__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPIX_IGATHERV = pmpix_igatherv_
#pragma weak pmpix_igatherv__ = pmpix_igatherv_
#pragma weak pmpix_igatherv = pmpix_igatherv_
#else
#pragma weak PMPIX_IGATHERV = pmpix_igatherv
#pragma weak pmpix_igatherv__ = pmpix_igatherv
#pragma weak pmpix_igatherv_ = pmpix_igatherv
#endif /* Test on name mapping */
#endif /* Use multiple pragma weak */

#ifdef F77_NAME_UPPER
#define mpix_igatherv_ PMPIX_IGATHERV
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_igatherv_ pmpix_igatherv__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_igatherv_ pmpix_igatherv
#else
#define mpix_igatherv_ pmpix_igatherv_
#endif /* Test on name mapping */

/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPIX_Igatherv
#define MPIX_Igatherv PMPIX_Igatherv 

#else

#ifdef F77_NAME_UPPER
#define mpix_igatherv_ MPIX_IGATHERV
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_igatherv_ mpix_igatherv__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_igatherv_ mpix_igatherv
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpix_igatherv_ ( void*v1, MPI_Fint *v2, MPI_Fint *v3, void*v4, MPI_Fint *v5, MPI_Fint *v6, MPI_Fint *v7, MPI_Fint *v8, MPI_Fint *v9, MPI_Fint *v10, MPI_Fint *ierr ){

#ifndef HAVE_MPI_F_INIT_WORKS_WITH_C
    if (MPIR_F_NeedInit){ mpirinitf_(); MPIR_F_NeedInit = 0; }
#endif
    if (v1 == MPIR_F_MPI_IN_PLACE) v1 = MPI_IN_PLACE;
    *ierr = MPIX_Igatherv( v1, *v2, (MPI_Datatype)(*v3), v4, v5, v6, (MPI_Datatype)(*v7), *v8, (MPI_Comm)(*v9), (MPI_Request *)(v10) );
}
