/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IGATHER( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_igather__( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_igather( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_igather_( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPIX_IGATHER = PMPIX_IGATHER
#pragma weak mpix_igather__ = PMPIX_IGATHER
#pragma weak mpix_igather_ = PMPIX_IGATHER
#pragma weak mpix_igather = PMPIX_IGATHER
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_IGATHER = pmpix_igather__
#pragma weak mpix_igather__ = pmpix_igather__
#pragma weak mpix_igather_ = pmpix_igather__
#pragma weak mpix_igather = pmpix_igather__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_IGATHER = pmpix_igather_
#pragma weak mpix_igather__ = pmpix_igather_
#pragma weak mpix_igather_ = pmpix_igather_
#pragma weak mpix_igather = pmpix_igather_
#else
#pragma weak MPIX_IGATHER = pmpix_igather
#pragma weak mpix_igather__ = pmpix_igather
#pragma weak mpix_igather_ = pmpix_igather
#pragma weak mpix_igather = pmpix_igather
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IGATHER( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPIX_IGATHER = PMPIX_IGATHER
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_igather__( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_igather__ = pmpix_igather__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_igather( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_igather = pmpix_igather
#else
extern FORT_DLL_SPEC void FORT_CALL mpix_igather_( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_igather_ = pmpix_igather_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPIX_IGATHER  MPIX_IGATHER
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpix_igather__  mpix_igather__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpix_igather  mpix_igather
#else
#pragma _HP_SECONDARY_DEF pmpix_igather_  mpix_igather_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPIX_IGATHER as PMPIX_IGATHER
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpix_igather__ as pmpix_igather__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpix_igather as pmpix_igather
#else
#pragma _CRI duplicate mpix_igather_ as pmpix_igather_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IGATHER( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_igather__( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_igather( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_igather_( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpix_igather__ = MPIX_IGATHER
#pragma weak mpix_igather_ = MPIX_IGATHER
#pragma weak mpix_igather = MPIX_IGATHER
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_IGATHER = mpix_igather__
#pragma weak mpix_igather_ = mpix_igather__
#pragma weak mpix_igather = mpix_igather__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_IGATHER = mpix_igather_
#pragma weak mpix_igather__ = mpix_igather_
#pragma weak mpix_igather = mpix_igather_
#else
#pragma weak MPIX_IGATHER = mpix_igather
#pragma weak mpix_igather__ = mpix_igather
#pragma weak mpix_igather_ = mpix_igather
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPIX_IGATHER( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_igather__( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_igather_( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpix_igather( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpix_igather__ = PMPIX_IGATHER
#pragma weak pmpix_igather_ = PMPIX_IGATHER
#pragma weak pmpix_igather = PMPIX_IGATHER
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPIX_IGATHER = pmpix_igather__
#pragma weak pmpix_igather_ = pmpix_igather__
#pragma weak pmpix_igather = pmpix_igather__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPIX_IGATHER = pmpix_igather_
#pragma weak pmpix_igather__ = pmpix_igather_
#pragma weak pmpix_igather = pmpix_igather_
#else
#pragma weak PMPIX_IGATHER = pmpix_igather
#pragma weak pmpix_igather__ = pmpix_igather
#pragma weak pmpix_igather_ = pmpix_igather
#endif /* Test on name mapping */
#endif /* Use multiple pragma weak */

#ifdef F77_NAME_UPPER
#define mpix_igather_ PMPIX_IGATHER
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_igather_ pmpix_igather__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_igather_ pmpix_igather
#else
#define mpix_igather_ pmpix_igather_
#endif /* Test on name mapping */

/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPIX_Igather
#define MPIX_Igather PMPIX_Igather 

#else

#ifdef F77_NAME_UPPER
#define mpix_igather_ MPIX_IGATHER
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_igather_ mpix_igather__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_igather_ mpix_igather
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpix_igather_ ( void*v1, MPI_Fint *v2, MPI_Fint *v3, void*v4, MPI_Fint *v5, MPI_Fint *v6, MPI_Fint *v7, MPI_Fint *v8, MPI_Fint *v9, MPI_Fint *ierr ){

#ifndef HAVE_MPI_F_INIT_WORKS_WITH_C
    if (MPIR_F_NeedInit){ mpirinitf_(); MPIR_F_NeedInit = 0; }
#endif
    if (v1 == MPIR_F_MPI_IN_PLACE) v1 = MPI_IN_PLACE;
    *ierr = MPIX_Igather( v1, *v2, (MPI_Datatype)(*v3), v4, *v5, (MPI_Datatype)(*v6), *v7, (MPI_Comm)(*v8), (MPI_Request *)(v9) );
}
