/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IMRECV( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_imrecv__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_imrecv( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_imrecv_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPIX_IMRECV = PMPIX_IMRECV
#pragma weak mpix_imrecv__ = PMPIX_IMRECV
#pragma weak mpix_imrecv_ = PMPIX_IMRECV
#pragma weak mpix_imrecv = PMPIX_IMRECV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_IMRECV = pmpix_imrecv__
#pragma weak mpix_imrecv__ = pmpix_imrecv__
#pragma weak mpix_imrecv_ = pmpix_imrecv__
#pragma weak mpix_imrecv = pmpix_imrecv__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_IMRECV = pmpix_imrecv_
#pragma weak mpix_imrecv__ = pmpix_imrecv_
#pragma weak mpix_imrecv_ = pmpix_imrecv_
#pragma weak mpix_imrecv = pmpix_imrecv_
#else
#pragma weak MPIX_IMRECV = pmpix_imrecv
#pragma weak mpix_imrecv__ = pmpix_imrecv
#pragma weak mpix_imrecv_ = pmpix_imrecv
#pragma weak mpix_imrecv = pmpix_imrecv
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IMRECV( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPIX_IMRECV = PMPIX_IMRECV
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_imrecv__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_imrecv__ = pmpix_imrecv__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_imrecv( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_imrecv = pmpix_imrecv
#else
extern FORT_DLL_SPEC void FORT_CALL mpix_imrecv_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_imrecv_ = pmpix_imrecv_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPIX_IMRECV  MPIX_IMRECV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpix_imrecv__  mpix_imrecv__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpix_imrecv  mpix_imrecv
#else
#pragma _HP_SECONDARY_DEF pmpix_imrecv_  mpix_imrecv_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPIX_IMRECV as PMPIX_IMRECV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpix_imrecv__ as pmpix_imrecv__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpix_imrecv as pmpix_imrecv
#else
#pragma _CRI duplicate mpix_imrecv_ as pmpix_imrecv_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IMRECV( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_imrecv__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_imrecv( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_imrecv_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpix_imrecv__ = MPIX_IMRECV
#pragma weak mpix_imrecv_ = MPIX_IMRECV
#pragma weak mpix_imrecv = MPIX_IMRECV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_IMRECV = mpix_imrecv__
#pragma weak mpix_imrecv_ = mpix_imrecv__
#pragma weak mpix_imrecv = mpix_imrecv__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_IMRECV = mpix_imrecv_
#pragma weak mpix_imrecv__ = mpix_imrecv_
#pragma weak mpix_imrecv = mpix_imrecv_
#else
#pragma weak MPIX_IMRECV = mpix_imrecv
#pragma weak mpix_imrecv__ = mpix_imrecv
#pragma weak mpix_imrecv_ = mpix_imrecv
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPIX_IMRECV( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_imrecv__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_imrecv_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpix_imrecv( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpix_imrecv__ = PMPIX_IMRECV
#pragma weak pmpix_imrecv_ = PMPIX_IMRECV
#pragma weak pmpix_imrecv = PMPIX_IMRECV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPIX_IMRECV = pmpix_imrecv__
#pragma weak pmpix_imrecv_ = pmpix_imrecv__
#pragma weak pmpix_imrecv = pmpix_imrecv__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPIX_IMRECV = pmpix_imrecv_
#pragma weak pmpix_imrecv__ = pmpix_imrecv_
#pragma weak pmpix_imrecv = pmpix_imrecv_
#else
#pragma weak PMPIX_IMRECV = pmpix_imrecv
#pragma weak pmpix_imrecv__ = pmpix_imrecv
#pragma weak pmpix_imrecv_ = pmpix_imrecv
#endif /* Test on name mapping */
#endif /* Use multiple pragma weak */

#ifdef F77_NAME_UPPER
#define mpix_imrecv_ PMPIX_IMRECV
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_imrecv_ pmpix_imrecv__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_imrecv_ pmpix_imrecv
#else
#define mpix_imrecv_ pmpix_imrecv_
#endif /* Test on name mapping */

/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPIX_Imrecv
#define MPIX_Imrecv PMPIX_Imrecv 

#else

#ifdef F77_NAME_UPPER
#define mpix_imrecv_ MPIX_IMRECV
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_imrecv_ mpix_imrecv__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_imrecv_ mpix_imrecv
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpix_imrecv_ ( void*v1, MPI_Fint *v2, MPI_Fint *v3, MPI_Fint *v4, MPI_Fint *v5, MPI_Fint *ierr ){
    *ierr = MPIX_Imrecv( v1, *v2, (MPI_Datatype)(*v3), (MPIX_Message *)(v4), (MPI_Request *)(v5) );
}
