/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IREDUCE_SCATTER( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ireduce_scatter__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ireduce_scatter( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ireduce_scatter_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPIX_IREDUCE_SCATTER = PMPIX_IREDUCE_SCATTER
#pragma weak mpix_ireduce_scatter__ = PMPIX_IREDUCE_SCATTER
#pragma weak mpix_ireduce_scatter_ = PMPIX_IREDUCE_SCATTER
#pragma weak mpix_ireduce_scatter = PMPIX_IREDUCE_SCATTER
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_IREDUCE_SCATTER = pmpix_ireduce_scatter__
#pragma weak mpix_ireduce_scatter__ = pmpix_ireduce_scatter__
#pragma weak mpix_ireduce_scatter_ = pmpix_ireduce_scatter__
#pragma weak mpix_ireduce_scatter = pmpix_ireduce_scatter__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_IREDUCE_SCATTER = pmpix_ireduce_scatter_
#pragma weak mpix_ireduce_scatter__ = pmpix_ireduce_scatter_
#pragma weak mpix_ireduce_scatter_ = pmpix_ireduce_scatter_
#pragma weak mpix_ireduce_scatter = pmpix_ireduce_scatter_
#else
#pragma weak MPIX_IREDUCE_SCATTER = pmpix_ireduce_scatter
#pragma weak mpix_ireduce_scatter__ = pmpix_ireduce_scatter
#pragma weak mpix_ireduce_scatter_ = pmpix_ireduce_scatter
#pragma weak mpix_ireduce_scatter = pmpix_ireduce_scatter
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IREDUCE_SCATTER( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPIX_IREDUCE_SCATTER = PMPIX_IREDUCE_SCATTER
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_ireduce_scatter__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_ireduce_scatter__ = pmpix_ireduce_scatter__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_ireduce_scatter( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_ireduce_scatter = pmpix_ireduce_scatter
#else
extern FORT_DLL_SPEC void FORT_CALL mpix_ireduce_scatter_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_ireduce_scatter_ = pmpix_ireduce_scatter_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPIX_IREDUCE_SCATTER  MPIX_IREDUCE_SCATTER
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpix_ireduce_scatter__  mpix_ireduce_scatter__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpix_ireduce_scatter  mpix_ireduce_scatter
#else
#pragma _HP_SECONDARY_DEF pmpix_ireduce_scatter_  mpix_ireduce_scatter_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPIX_IREDUCE_SCATTER as PMPIX_IREDUCE_SCATTER
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpix_ireduce_scatter__ as pmpix_ireduce_scatter__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpix_ireduce_scatter as pmpix_ireduce_scatter
#else
#pragma _CRI duplicate mpix_ireduce_scatter_ as pmpix_ireduce_scatter_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPIX_IREDUCE_SCATTER( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ireduce_scatter__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ireduce_scatter( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_ireduce_scatter_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpix_ireduce_scatter__ = MPIX_IREDUCE_SCATTER
#pragma weak mpix_ireduce_scatter_ = MPIX_IREDUCE_SCATTER
#pragma weak mpix_ireduce_scatter = MPIX_IREDUCE_SCATTER
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_IREDUCE_SCATTER = mpix_ireduce_scatter__
#pragma weak mpix_ireduce_scatter_ = mpix_ireduce_scatter__
#pragma weak mpix_ireduce_scatter = mpix_ireduce_scatter__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_IREDUCE_SCATTER = mpix_ireduce_scatter_
#pragma weak mpix_ireduce_scatter__ = mpix_ireduce_scatter_
#pragma weak mpix_ireduce_scatter = mpix_ireduce_scatter_
#else
#pragma weak MPIX_IREDUCE_SCATTER = mpix_ireduce_scatter
#pragma weak mpix_ireduce_scatter__ = mpix_ireduce_scatter
#pragma weak mpix_ireduce_scatter_ = mpix_ireduce_scatter
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPIX_IREDUCE_SCATTER( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_ireduce_scatter__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_ireduce_scatter_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpix_ireduce_scatter( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpix_ireduce_scatter__ = PMPIX_IREDUCE_SCATTER
#pragma weak pmpix_ireduce_scatter_ = PMPIX_IREDUCE_SCATTER
#pragma weak pmpix_ireduce_scatter = PMPIX_IREDUCE_SCATTER
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPIX_IREDUCE_SCATTER = pmpix_ireduce_scatter__
#pragma weak pmpix_ireduce_scatter_ = pmpix_ireduce_scatter__
#pragma weak pmpix_ireduce_scatter = pmpix_ireduce_scatter__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPIX_IREDUCE_SCATTER = pmpix_ireduce_scatter_
#pragma weak pmpix_ireduce_scatter__ = pmpix_ireduce_scatter_
#pragma weak pmpix_ireduce_scatter = pmpix_ireduce_scatter_
#else
#pragma weak PMPIX_IREDUCE_SCATTER = pmpix_ireduce_scatter
#pragma weak pmpix_ireduce_scatter__ = pmpix_ireduce_scatter
#pragma weak pmpix_ireduce_scatter_ = pmpix_ireduce_scatter
#endif /* Test on name mapping */
#endif /* Use multiple pragma weak */

#ifdef F77_NAME_UPPER
#define mpix_ireduce_scatter_ PMPIX_IREDUCE_SCATTER
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_ireduce_scatter_ pmpix_ireduce_scatter__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_ireduce_scatter_ pmpix_ireduce_scatter
#else
#define mpix_ireduce_scatter_ pmpix_ireduce_scatter_
#endif /* Test on name mapping */

/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPIX_Ireduce_scatter
#define MPIX_Ireduce_scatter PMPIX_Ireduce_scatter 

#else

#ifdef F77_NAME_UPPER
#define mpix_ireduce_scatter_ MPIX_IREDUCE_SCATTER
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_ireduce_scatter_ mpix_ireduce_scatter__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_ireduce_scatter_ mpix_ireduce_scatter
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpix_ireduce_scatter_ ( void*v1, void*v2, MPI_Fint *v3, MPI_Fint *v4, MPI_Fint *v5, MPI_Fint *v6, MPI_Fint *v7, MPI_Fint *ierr ){

#ifndef HAVE_MPI_F_INIT_WORKS_WITH_C
    if (MPIR_F_NeedInit){ mpirinitf_(); MPIR_F_NeedInit = 0; }
#endif
    if (v1 == MPIR_F_MPI_IN_PLACE) v1 = MPI_IN_PLACE;
    *ierr = MPIX_Ireduce_scatter( v1, v2, v3, (MPI_Datatype)(*v4), *v5, (MPI_Comm)(*v6), (MPI_Request *)(v7) );
}
