/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_ISCAN( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iscan__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iscan( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iscan_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPIX_ISCAN = PMPIX_ISCAN
#pragma weak mpix_iscan__ = PMPIX_ISCAN
#pragma weak mpix_iscan_ = PMPIX_ISCAN
#pragma weak mpix_iscan = PMPIX_ISCAN
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_ISCAN = pmpix_iscan__
#pragma weak mpix_iscan__ = pmpix_iscan__
#pragma weak mpix_iscan_ = pmpix_iscan__
#pragma weak mpix_iscan = pmpix_iscan__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_ISCAN = pmpix_iscan_
#pragma weak mpix_iscan__ = pmpix_iscan_
#pragma weak mpix_iscan_ = pmpix_iscan_
#pragma weak mpix_iscan = pmpix_iscan_
#else
#pragma weak MPIX_ISCAN = pmpix_iscan
#pragma weak mpix_iscan__ = pmpix_iscan
#pragma weak mpix_iscan_ = pmpix_iscan
#pragma weak mpix_iscan = pmpix_iscan
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_ISCAN( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPIX_ISCAN = PMPIX_ISCAN
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_iscan__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_iscan__ = pmpix_iscan__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_iscan( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_iscan = pmpix_iscan
#else
extern FORT_DLL_SPEC void FORT_CALL mpix_iscan_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_iscan_ = pmpix_iscan_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPIX_ISCAN  MPIX_ISCAN
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpix_iscan__  mpix_iscan__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpix_iscan  mpix_iscan
#else
#pragma _HP_SECONDARY_DEF pmpix_iscan_  mpix_iscan_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPIX_ISCAN as PMPIX_ISCAN
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpix_iscan__ as pmpix_iscan__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpix_iscan as pmpix_iscan
#else
#pragma _CRI duplicate mpix_iscan_ as pmpix_iscan_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPIX_ISCAN( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iscan__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iscan( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iscan_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpix_iscan__ = MPIX_ISCAN
#pragma weak mpix_iscan_ = MPIX_ISCAN
#pragma weak mpix_iscan = MPIX_ISCAN
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_ISCAN = mpix_iscan__
#pragma weak mpix_iscan_ = mpix_iscan__
#pragma weak mpix_iscan = mpix_iscan__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_ISCAN = mpix_iscan_
#pragma weak mpix_iscan__ = mpix_iscan_
#pragma weak mpix_iscan = mpix_iscan_
#else
#pragma weak MPIX_ISCAN = mpix_iscan
#pragma weak mpix_iscan__ = mpix_iscan
#pragma weak mpix_iscan_ = mpix_iscan
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPIX_ISCAN( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_iscan__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_iscan_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpix_iscan( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpix_iscan__ = PMPIX_ISCAN
#pragma weak pmpix_iscan_ = PMPIX_ISCAN
#pragma weak pmpix_iscan = PMPIX_ISCAN
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPIX_ISCAN = pmpix_iscan__
#pragma weak pmpix_iscan_ = pmpix_iscan__
#pragma weak pmpix_iscan = pmpix_iscan__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPIX_ISCAN = pmpix_iscan_
#pragma weak pmpix_iscan__ = pmpix_iscan_
#pragma weak pmpix_iscan = pmpix_iscan_
#else
#pragma weak PMPIX_ISCAN = pmpix_iscan
#pragma weak pmpix_iscan__ = pmpix_iscan
#pragma weak pmpix_iscan_ = pmpix_iscan
#endif /* Test on name mapping */
#endif /* Use multiple pragma weak */

#ifdef F77_NAME_UPPER
#define mpix_iscan_ PMPIX_ISCAN
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_iscan_ pmpix_iscan__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_iscan_ pmpix_iscan
#else
#define mpix_iscan_ pmpix_iscan_
#endif /* Test on name mapping */

/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPIX_Iscan
#define MPIX_Iscan PMPIX_Iscan 

#else

#ifdef F77_NAME_UPPER
#define mpix_iscan_ MPIX_ISCAN
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_iscan_ mpix_iscan__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_iscan_ mpix_iscan
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpix_iscan_ ( void*v1, void*v2, MPI_Fint *v3, MPI_Fint *v4, MPI_Fint *v5, MPI_Fint *v6, MPI_Fint *v7, MPI_Fint *ierr ){

#ifndef HAVE_MPI_F_INIT_WORKS_WITH_C
    if (MPIR_F_NeedInit){ mpirinitf_(); MPIR_F_NeedInit = 0; }
#endif
    if (v1 == MPIR_F_MPI_IN_PLACE) v1 = MPI_IN_PLACE;
    *ierr = MPIX_Iscan( v1, v2, *v3, (MPI_Datatype)(*v4), *v5, (MPI_Comm)(*v6), (MPI_Request *)(v7) );
}
