/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_ISCATTER( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iscatter__( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iscatter( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iscatter_( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPIX_ISCATTER = PMPIX_ISCATTER
#pragma weak mpix_iscatter__ = PMPIX_ISCATTER
#pragma weak mpix_iscatter_ = PMPIX_ISCATTER
#pragma weak mpix_iscatter = PMPIX_ISCATTER
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_ISCATTER = pmpix_iscatter__
#pragma weak mpix_iscatter__ = pmpix_iscatter__
#pragma weak mpix_iscatter_ = pmpix_iscatter__
#pragma weak mpix_iscatter = pmpix_iscatter__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_ISCATTER = pmpix_iscatter_
#pragma weak mpix_iscatter__ = pmpix_iscatter_
#pragma weak mpix_iscatter_ = pmpix_iscatter_
#pragma weak mpix_iscatter = pmpix_iscatter_
#else
#pragma weak MPIX_ISCATTER = pmpix_iscatter
#pragma weak mpix_iscatter__ = pmpix_iscatter
#pragma weak mpix_iscatter_ = pmpix_iscatter
#pragma weak mpix_iscatter = pmpix_iscatter
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_ISCATTER( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPIX_ISCATTER = PMPIX_ISCATTER
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_iscatter__( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_iscatter__ = pmpix_iscatter__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_iscatter( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_iscatter = pmpix_iscatter
#else
extern FORT_DLL_SPEC void FORT_CALL mpix_iscatter_( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_iscatter_ = pmpix_iscatter_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPIX_ISCATTER  MPIX_ISCATTER
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpix_iscatter__  mpix_iscatter__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpix_iscatter  mpix_iscatter
#else
#pragma _HP_SECONDARY_DEF pmpix_iscatter_  mpix_iscatter_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPIX_ISCATTER as PMPIX_ISCATTER
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpix_iscatter__ as pmpix_iscatter__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpix_iscatter as pmpix_iscatter
#else
#pragma _CRI duplicate mpix_iscatter_ as pmpix_iscatter_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPIX_ISCATTER( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iscatter__( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iscatter( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_iscatter_( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpix_iscatter__ = MPIX_ISCATTER
#pragma weak mpix_iscatter_ = MPIX_ISCATTER
#pragma weak mpix_iscatter = MPIX_ISCATTER
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_ISCATTER = mpix_iscatter__
#pragma weak mpix_iscatter_ = mpix_iscatter__
#pragma weak mpix_iscatter = mpix_iscatter__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_ISCATTER = mpix_iscatter_
#pragma weak mpix_iscatter__ = mpix_iscatter_
#pragma weak mpix_iscatter = mpix_iscatter_
#else
#pragma weak MPIX_ISCATTER = mpix_iscatter
#pragma weak mpix_iscatter__ = mpix_iscatter
#pragma weak mpix_iscatter_ = mpix_iscatter
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPIX_ISCATTER( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_iscatter__( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_iscatter_( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpix_iscatter( void*, MPI_Fint *, MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpix_iscatter__ = PMPIX_ISCATTER
#pragma weak pmpix_iscatter_ = PMPIX_ISCATTER
#pragma weak pmpix_iscatter = PMPIX_ISCATTER
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPIX_ISCATTER = pmpix_iscatter__
#pragma weak pmpix_iscatter_ = pmpix_iscatter__
#pragma weak pmpix_iscatter = pmpix_iscatter__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPIX_ISCATTER = pmpix_iscatter_
#pragma weak pmpix_iscatter__ = pmpix_iscatter_
#pragma weak pmpix_iscatter = pmpix_iscatter_
#else
#pragma weak PMPIX_ISCATTER = pmpix_iscatter
#pragma weak pmpix_iscatter__ = pmpix_iscatter
#pragma weak pmpix_iscatter_ = pmpix_iscatter
#endif /* Test on name mapping */
#endif /* Use multiple pragma weak */

#ifdef F77_NAME_UPPER
#define mpix_iscatter_ PMPIX_ISCATTER
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_iscatter_ pmpix_iscatter__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_iscatter_ pmpix_iscatter
#else
#define mpix_iscatter_ pmpix_iscatter_
#endif /* Test on name mapping */

/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPIX_Iscatter
#define MPIX_Iscatter PMPIX_Iscatter 

#else

#ifdef F77_NAME_UPPER
#define mpix_iscatter_ MPIX_ISCATTER
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_iscatter_ mpix_iscatter__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_iscatter_ mpix_iscatter
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpix_iscatter_ ( void*v1, MPI_Fint *v2, MPI_Fint *v3, void*v4, MPI_Fint *v5, MPI_Fint *v6, MPI_Fint *v7, MPI_Fint *v8, MPI_Fint *v9, MPI_Fint *ierr ){

#ifndef HAVE_MPI_F_INIT_WORKS_WITH_C
    if (MPIR_F_NeedInit){ mpirinitf_(); MPIR_F_NeedInit = 0; }
#endif
    if (v4 == MPIR_F_MPI_IN_PLACE) v4 = MPI_IN_PLACE;
    *ierr = MPIX_Iscatter( v1, *v2, (MPI_Datatype)(*v3), v4, *v5, (MPI_Datatype)(*v6), *v7, (MPI_Comm)(*v8), (MPI_Request *)(v9) );
}
