/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_MPROBE( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_mprobe__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_mprobe( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_mprobe_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPIX_MPROBE = PMPIX_MPROBE
#pragma weak mpix_mprobe__ = PMPIX_MPROBE
#pragma weak mpix_mprobe_ = PMPIX_MPROBE
#pragma weak mpix_mprobe = PMPIX_MPROBE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_MPROBE = pmpix_mprobe__
#pragma weak mpix_mprobe__ = pmpix_mprobe__
#pragma weak mpix_mprobe_ = pmpix_mprobe__
#pragma weak mpix_mprobe = pmpix_mprobe__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_MPROBE = pmpix_mprobe_
#pragma weak mpix_mprobe__ = pmpix_mprobe_
#pragma weak mpix_mprobe_ = pmpix_mprobe_
#pragma weak mpix_mprobe = pmpix_mprobe_
#else
#pragma weak MPIX_MPROBE = pmpix_mprobe
#pragma weak mpix_mprobe__ = pmpix_mprobe
#pragma weak mpix_mprobe_ = pmpix_mprobe
#pragma weak mpix_mprobe = pmpix_mprobe
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_MPROBE( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPIX_MPROBE = PMPIX_MPROBE
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_mprobe__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_mprobe__ = pmpix_mprobe__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_mprobe( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_mprobe = pmpix_mprobe
#else
extern FORT_DLL_SPEC void FORT_CALL mpix_mprobe_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_mprobe_ = pmpix_mprobe_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPIX_MPROBE  MPIX_MPROBE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpix_mprobe__  mpix_mprobe__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpix_mprobe  mpix_mprobe
#else
#pragma _HP_SECONDARY_DEF pmpix_mprobe_  mpix_mprobe_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPIX_MPROBE as PMPIX_MPROBE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpix_mprobe__ as pmpix_mprobe__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpix_mprobe as pmpix_mprobe
#else
#pragma _CRI duplicate mpix_mprobe_ as pmpix_mprobe_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPIX_MPROBE( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_mprobe__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_mprobe( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_mprobe_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpix_mprobe__ = MPIX_MPROBE
#pragma weak mpix_mprobe_ = MPIX_MPROBE
#pragma weak mpix_mprobe = MPIX_MPROBE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_MPROBE = mpix_mprobe__
#pragma weak mpix_mprobe_ = mpix_mprobe__
#pragma weak mpix_mprobe = mpix_mprobe__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_MPROBE = mpix_mprobe_
#pragma weak mpix_mprobe__ = mpix_mprobe_
#pragma weak mpix_mprobe = mpix_mprobe_
#else
#pragma weak MPIX_MPROBE = mpix_mprobe
#pragma weak mpix_mprobe__ = mpix_mprobe
#pragma weak mpix_mprobe_ = mpix_mprobe
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPIX_MPROBE( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_mprobe__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_mprobe_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpix_mprobe( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpix_mprobe__ = PMPIX_MPROBE
#pragma weak pmpix_mprobe_ = PMPIX_MPROBE
#pragma weak pmpix_mprobe = PMPIX_MPROBE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPIX_MPROBE = pmpix_mprobe__
#pragma weak pmpix_mprobe_ = pmpix_mprobe__
#pragma weak pmpix_mprobe = pmpix_mprobe__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPIX_MPROBE = pmpix_mprobe_
#pragma weak pmpix_mprobe__ = pmpix_mprobe_
#pragma weak pmpix_mprobe = pmpix_mprobe_
#else
#pragma weak PMPIX_MPROBE = pmpix_mprobe
#pragma weak pmpix_mprobe__ = pmpix_mprobe
#pragma weak pmpix_mprobe_ = pmpix_mprobe
#endif /* Test on name mapping */
#endif /* Use multiple pragma weak */

#ifdef F77_NAME_UPPER
#define mpix_mprobe_ PMPIX_MPROBE
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_mprobe_ pmpix_mprobe__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_mprobe_ pmpix_mprobe
#else
#define mpix_mprobe_ pmpix_mprobe_
#endif /* Test on name mapping */

/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPIX_Mprobe
#define MPIX_Mprobe PMPIX_Mprobe 

#else

#ifdef F77_NAME_UPPER
#define mpix_mprobe_ MPIX_MPROBE
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_mprobe_ mpix_mprobe__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_mprobe_ mpix_mprobe
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpix_mprobe_ ( MPI_Fint *v1, MPI_Fint *v2, MPI_Fint *v3, MPI_Fint *v4, MPI_Fint *v5, MPI_Fint *ierr ){

#ifndef HAVE_MPI_F_INIT_WORKS_WITH_C
    if (MPIR_F_NeedInit){ mpirinitf_(); MPIR_F_NeedInit = 0; }
#endif

    if (v5 == MPI_F_STATUS_IGNORE) { v5 = (MPI_Fint*)MPI_STATUS_IGNORE; }
    *ierr = MPIX_Mprobe( *v1, *v2, (MPI_Comm)(*v3), (MPIX_Message *)(v4), (MPI_Status *)v5 );
}
