/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_MRECV( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_mrecv__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_mrecv( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_mrecv_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPIX_MRECV = PMPIX_MRECV
#pragma weak mpix_mrecv__ = PMPIX_MRECV
#pragma weak mpix_mrecv_ = PMPIX_MRECV
#pragma weak mpix_mrecv = PMPIX_MRECV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_MRECV = pmpix_mrecv__
#pragma weak mpix_mrecv__ = pmpix_mrecv__
#pragma weak mpix_mrecv_ = pmpix_mrecv__
#pragma weak mpix_mrecv = pmpix_mrecv__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_MRECV = pmpix_mrecv_
#pragma weak mpix_mrecv__ = pmpix_mrecv_
#pragma weak mpix_mrecv_ = pmpix_mrecv_
#pragma weak mpix_mrecv = pmpix_mrecv_
#else
#pragma weak MPIX_MRECV = pmpix_mrecv
#pragma weak mpix_mrecv__ = pmpix_mrecv
#pragma weak mpix_mrecv_ = pmpix_mrecv
#pragma weak mpix_mrecv = pmpix_mrecv
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_MRECV( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPIX_MRECV = PMPIX_MRECV
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_mrecv__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_mrecv__ = pmpix_mrecv__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_mrecv( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_mrecv = pmpix_mrecv
#else
extern FORT_DLL_SPEC void FORT_CALL mpix_mrecv_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_mrecv_ = pmpix_mrecv_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPIX_MRECV  MPIX_MRECV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpix_mrecv__  mpix_mrecv__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpix_mrecv  mpix_mrecv
#else
#pragma _HP_SECONDARY_DEF pmpix_mrecv_  mpix_mrecv_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPIX_MRECV as PMPIX_MRECV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpix_mrecv__ as pmpix_mrecv__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpix_mrecv as pmpix_mrecv
#else
#pragma _CRI duplicate mpix_mrecv_ as pmpix_mrecv_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPIX_MRECV( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_mrecv__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_mrecv( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_mrecv_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpix_mrecv__ = MPIX_MRECV
#pragma weak mpix_mrecv_ = MPIX_MRECV
#pragma weak mpix_mrecv = MPIX_MRECV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_MRECV = mpix_mrecv__
#pragma weak mpix_mrecv_ = mpix_mrecv__
#pragma weak mpix_mrecv = mpix_mrecv__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_MRECV = mpix_mrecv_
#pragma weak mpix_mrecv__ = mpix_mrecv_
#pragma weak mpix_mrecv = mpix_mrecv_
#else
#pragma weak MPIX_MRECV = mpix_mrecv
#pragma weak mpix_mrecv__ = mpix_mrecv
#pragma weak mpix_mrecv_ = mpix_mrecv
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPIX_MRECV( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_mrecv__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_mrecv_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpix_mrecv( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpix_mrecv__ = PMPIX_MRECV
#pragma weak pmpix_mrecv_ = PMPIX_MRECV
#pragma weak pmpix_mrecv = PMPIX_MRECV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPIX_MRECV = pmpix_mrecv__
#pragma weak pmpix_mrecv_ = pmpix_mrecv__
#pragma weak pmpix_mrecv = pmpix_mrecv__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPIX_MRECV = pmpix_mrecv_
#pragma weak pmpix_mrecv__ = pmpix_mrecv_
#pragma weak pmpix_mrecv = pmpix_mrecv_
#else
#pragma weak PMPIX_MRECV = pmpix_mrecv
#pragma weak pmpix_mrecv__ = pmpix_mrecv
#pragma weak pmpix_mrecv_ = pmpix_mrecv
#endif /* Test on name mapping */
#endif /* Use multiple pragma weak */

#ifdef F77_NAME_UPPER
#define mpix_mrecv_ PMPIX_MRECV
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_mrecv_ pmpix_mrecv__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_mrecv_ pmpix_mrecv
#else
#define mpix_mrecv_ pmpix_mrecv_
#endif /* Test on name mapping */

/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPIX_Mrecv
#define MPIX_Mrecv PMPIX_Mrecv 

#else

#ifdef F77_NAME_UPPER
#define mpix_mrecv_ MPIX_MRECV
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_mrecv_ mpix_mrecv__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_mrecv_ mpix_mrecv
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpix_mrecv_ ( void*v1, MPI_Fint *v2, MPI_Fint *v3, MPI_Fint *v4, MPI_Fint *v5, MPI_Fint *ierr ){

#ifndef HAVE_MPI_F_INIT_WORKS_WITH_C
    if (MPIR_F_NeedInit){ mpirinitf_(); MPIR_F_NeedInit = 0; }
#endif

    if (v5 == MPI_F_STATUS_IGNORE) { v5 = (MPI_Fint*)MPI_STATUS_IGNORE; }
    *ierr = MPIX_Mrecv( v1, *v2, (MPI_Datatype)(*v3), (MPIX_Message *)(v4), (MPI_Status *)v5 );
}
