/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_MUTEX_CREATE( MPI_Fint *, MPI_Fint *, MPIX_Mutex*, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_mutex_create__( MPI_Fint *, MPI_Fint *, MPIX_Mutex*, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_mutex_create( MPI_Fint *, MPI_Fint *, MPIX_Mutex*, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_mutex_create_( MPI_Fint *, MPI_Fint *, MPIX_Mutex*, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPIX_MUTEX_CREATE = PMPIX_MUTEX_CREATE
#pragma weak mpix_mutex_create__ = PMPIX_MUTEX_CREATE
#pragma weak mpix_mutex_create_ = PMPIX_MUTEX_CREATE
#pragma weak mpix_mutex_create = PMPIX_MUTEX_CREATE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_MUTEX_CREATE = pmpix_mutex_create__
#pragma weak mpix_mutex_create__ = pmpix_mutex_create__
#pragma weak mpix_mutex_create_ = pmpix_mutex_create__
#pragma weak mpix_mutex_create = pmpix_mutex_create__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_MUTEX_CREATE = pmpix_mutex_create_
#pragma weak mpix_mutex_create__ = pmpix_mutex_create_
#pragma weak mpix_mutex_create_ = pmpix_mutex_create_
#pragma weak mpix_mutex_create = pmpix_mutex_create_
#else
#pragma weak MPIX_MUTEX_CREATE = pmpix_mutex_create
#pragma weak mpix_mutex_create__ = pmpix_mutex_create
#pragma weak mpix_mutex_create_ = pmpix_mutex_create
#pragma weak mpix_mutex_create = pmpix_mutex_create
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_MUTEX_CREATE( MPI_Fint *, MPI_Fint *, MPIX_Mutex*, MPI_Fint * );

#pragma weak MPIX_MUTEX_CREATE = PMPIX_MUTEX_CREATE
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_mutex_create__( MPI_Fint *, MPI_Fint *, MPIX_Mutex*, MPI_Fint * );

#pragma weak mpix_mutex_create__ = pmpix_mutex_create__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_mutex_create( MPI_Fint *, MPI_Fint *, MPIX_Mutex*, MPI_Fint * );

#pragma weak mpix_mutex_create = pmpix_mutex_create
#else
extern FORT_DLL_SPEC void FORT_CALL mpix_mutex_create_( MPI_Fint *, MPI_Fint *, MPIX_Mutex*, MPI_Fint * );

#pragma weak mpix_mutex_create_ = pmpix_mutex_create_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPIX_MUTEX_CREATE  MPIX_MUTEX_CREATE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpix_mutex_create__  mpix_mutex_create__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpix_mutex_create  mpix_mutex_create
#else
#pragma _HP_SECONDARY_DEF pmpix_mutex_create_  mpix_mutex_create_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPIX_MUTEX_CREATE as PMPIX_MUTEX_CREATE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpix_mutex_create__ as pmpix_mutex_create__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpix_mutex_create as pmpix_mutex_create
#else
#pragma _CRI duplicate mpix_mutex_create_ as pmpix_mutex_create_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPIX_MUTEX_CREATE( MPI_Fint *, MPI_Fint *, MPIX_Mutex*, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_mutex_create__( MPI_Fint *, MPI_Fint *, MPIX_Mutex*, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_mutex_create( MPI_Fint *, MPI_Fint *, MPIX_Mutex*, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_mutex_create_( MPI_Fint *, MPI_Fint *, MPIX_Mutex*, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpix_mutex_create__ = MPIX_MUTEX_CREATE
#pragma weak mpix_mutex_create_ = MPIX_MUTEX_CREATE
#pragma weak mpix_mutex_create = MPIX_MUTEX_CREATE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_MUTEX_CREATE = mpix_mutex_create__
#pragma weak mpix_mutex_create_ = mpix_mutex_create__
#pragma weak mpix_mutex_create = mpix_mutex_create__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_MUTEX_CREATE = mpix_mutex_create_
#pragma weak mpix_mutex_create__ = mpix_mutex_create_
#pragma weak mpix_mutex_create = mpix_mutex_create_
#else
#pragma weak MPIX_MUTEX_CREATE = mpix_mutex_create
#pragma weak mpix_mutex_create__ = mpix_mutex_create
#pragma weak mpix_mutex_create_ = mpix_mutex_create
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPIX_MUTEX_CREATE( MPI_Fint *, MPI_Fint *, MPIX_Mutex*, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_mutex_create__( MPI_Fint *, MPI_Fint *, MPIX_Mutex*, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_mutex_create_( MPI_Fint *, MPI_Fint *, MPIX_Mutex*, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpix_mutex_create( MPI_Fint *, MPI_Fint *, MPIX_Mutex*, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpix_mutex_create__ = PMPIX_MUTEX_CREATE
#pragma weak pmpix_mutex_create_ = PMPIX_MUTEX_CREATE
#pragma weak pmpix_mutex_create = PMPIX_MUTEX_CREATE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPIX_MUTEX_CREATE = pmpix_mutex_create__
#pragma weak pmpix_mutex_create_ = pmpix_mutex_create__
#pragma weak pmpix_mutex_create = pmpix_mutex_create__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPIX_MUTEX_CREATE = pmpix_mutex_create_
#pragma weak pmpix_mutex_create__ = pmpix_mutex_create_
#pragma weak pmpix_mutex_create = pmpix_mutex_create_
#else
#pragma weak PMPIX_MUTEX_CREATE = pmpix_mutex_create
#pragma weak pmpix_mutex_create__ = pmpix_mutex_create
#pragma weak pmpix_mutex_create_ = pmpix_mutex_create
#endif /* Test on name mapping */
#endif /* Use multiple pragma weak */

#ifdef F77_NAME_UPPER
#define mpix_mutex_create_ PMPIX_MUTEX_CREATE
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_mutex_create_ pmpix_mutex_create__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_mutex_create_ pmpix_mutex_create
#else
#define mpix_mutex_create_ pmpix_mutex_create_
#endif /* Test on name mapping */

/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPIX_Mutex_create
#define MPIX_Mutex_create PMPIX_Mutex_create 

#else

#ifdef F77_NAME_UPPER
#define mpix_mutex_create_ MPIX_MUTEX_CREATE
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_mutex_create_ mpix_mutex_create__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_mutex_create_ mpix_mutex_create
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpix_mutex_create_ ( MPI_Fint *v1, MPI_Fint *v2, MPIX_Mutex*v3, MPI_Fint *ierr ){
    *ierr = MPIX_Mutex_create( *v1, (MPI_Comm)(*v2), v3 );
}
