/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_MUTEX_FREE( MPIX_Mutex*, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_mutex_free__( MPIX_Mutex*, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_mutex_free( MPIX_Mutex*, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_mutex_free_( MPIX_Mutex*, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPIX_MUTEX_FREE = PMPIX_MUTEX_FREE
#pragma weak mpix_mutex_free__ = PMPIX_MUTEX_FREE
#pragma weak mpix_mutex_free_ = PMPIX_MUTEX_FREE
#pragma weak mpix_mutex_free = PMPIX_MUTEX_FREE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_MUTEX_FREE = pmpix_mutex_free__
#pragma weak mpix_mutex_free__ = pmpix_mutex_free__
#pragma weak mpix_mutex_free_ = pmpix_mutex_free__
#pragma weak mpix_mutex_free = pmpix_mutex_free__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_MUTEX_FREE = pmpix_mutex_free_
#pragma weak mpix_mutex_free__ = pmpix_mutex_free_
#pragma weak mpix_mutex_free_ = pmpix_mutex_free_
#pragma weak mpix_mutex_free = pmpix_mutex_free_
#else
#pragma weak MPIX_MUTEX_FREE = pmpix_mutex_free
#pragma weak mpix_mutex_free__ = pmpix_mutex_free
#pragma weak mpix_mutex_free_ = pmpix_mutex_free
#pragma weak mpix_mutex_free = pmpix_mutex_free
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_MUTEX_FREE( MPIX_Mutex*, MPI_Fint * );

#pragma weak MPIX_MUTEX_FREE = PMPIX_MUTEX_FREE
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_mutex_free__( MPIX_Mutex*, MPI_Fint * );

#pragma weak mpix_mutex_free__ = pmpix_mutex_free__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_mutex_free( MPIX_Mutex*, MPI_Fint * );

#pragma weak mpix_mutex_free = pmpix_mutex_free
#else
extern FORT_DLL_SPEC void FORT_CALL mpix_mutex_free_( MPIX_Mutex*, MPI_Fint * );

#pragma weak mpix_mutex_free_ = pmpix_mutex_free_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPIX_MUTEX_FREE  MPIX_MUTEX_FREE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpix_mutex_free__  mpix_mutex_free__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpix_mutex_free  mpix_mutex_free
#else
#pragma _HP_SECONDARY_DEF pmpix_mutex_free_  mpix_mutex_free_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPIX_MUTEX_FREE as PMPIX_MUTEX_FREE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpix_mutex_free__ as pmpix_mutex_free__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpix_mutex_free as pmpix_mutex_free
#else
#pragma _CRI duplicate mpix_mutex_free_ as pmpix_mutex_free_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPIX_MUTEX_FREE( MPIX_Mutex*, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_mutex_free__( MPIX_Mutex*, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_mutex_free( MPIX_Mutex*, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_mutex_free_( MPIX_Mutex*, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpix_mutex_free__ = MPIX_MUTEX_FREE
#pragma weak mpix_mutex_free_ = MPIX_MUTEX_FREE
#pragma weak mpix_mutex_free = MPIX_MUTEX_FREE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_MUTEX_FREE = mpix_mutex_free__
#pragma weak mpix_mutex_free_ = mpix_mutex_free__
#pragma weak mpix_mutex_free = mpix_mutex_free__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_MUTEX_FREE = mpix_mutex_free_
#pragma weak mpix_mutex_free__ = mpix_mutex_free_
#pragma weak mpix_mutex_free = mpix_mutex_free_
#else
#pragma weak MPIX_MUTEX_FREE = mpix_mutex_free
#pragma weak mpix_mutex_free__ = mpix_mutex_free
#pragma weak mpix_mutex_free_ = mpix_mutex_free
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPIX_MUTEX_FREE( MPIX_Mutex*, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_mutex_free__( MPIX_Mutex*, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_mutex_free_( MPIX_Mutex*, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpix_mutex_free( MPIX_Mutex*, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpix_mutex_free__ = PMPIX_MUTEX_FREE
#pragma weak pmpix_mutex_free_ = PMPIX_MUTEX_FREE
#pragma weak pmpix_mutex_free = PMPIX_MUTEX_FREE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPIX_MUTEX_FREE = pmpix_mutex_free__
#pragma weak pmpix_mutex_free_ = pmpix_mutex_free__
#pragma weak pmpix_mutex_free = pmpix_mutex_free__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPIX_MUTEX_FREE = pmpix_mutex_free_
#pragma weak pmpix_mutex_free__ = pmpix_mutex_free_
#pragma weak pmpix_mutex_free = pmpix_mutex_free_
#else
#pragma weak PMPIX_MUTEX_FREE = pmpix_mutex_free
#pragma weak pmpix_mutex_free__ = pmpix_mutex_free
#pragma weak pmpix_mutex_free_ = pmpix_mutex_free
#endif /* Test on name mapping */
#endif /* Use multiple pragma weak */

#ifdef F77_NAME_UPPER
#define mpix_mutex_free_ PMPIX_MUTEX_FREE
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_mutex_free_ pmpix_mutex_free__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_mutex_free_ pmpix_mutex_free
#else
#define mpix_mutex_free_ pmpix_mutex_free_
#endif /* Test on name mapping */

/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPIX_Mutex_free
#define MPIX_Mutex_free PMPIX_Mutex_free 

#else

#ifdef F77_NAME_UPPER
#define mpix_mutex_free_ MPIX_MUTEX_FREE
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_mutex_free_ mpix_mutex_free__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_mutex_free_ mpix_mutex_free
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpix_mutex_free_ ( MPIX_Mutex*v1, MPI_Fint *ierr ){
    *ierr = MPIX_Mutex_free( v1 );
}
