/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_NEIGHBOR_ALLTOALLV( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_neighbor_alltoallv__( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_neighbor_alltoallv( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_neighbor_alltoallv_( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPIX_NEIGHBOR_ALLTOALLV = PMPIX_NEIGHBOR_ALLTOALLV
#pragma weak mpix_neighbor_alltoallv__ = PMPIX_NEIGHBOR_ALLTOALLV
#pragma weak mpix_neighbor_alltoallv_ = PMPIX_NEIGHBOR_ALLTOALLV
#pragma weak mpix_neighbor_alltoallv = PMPIX_NEIGHBOR_ALLTOALLV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_NEIGHBOR_ALLTOALLV = pmpix_neighbor_alltoallv__
#pragma weak mpix_neighbor_alltoallv__ = pmpix_neighbor_alltoallv__
#pragma weak mpix_neighbor_alltoallv_ = pmpix_neighbor_alltoallv__
#pragma weak mpix_neighbor_alltoallv = pmpix_neighbor_alltoallv__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_NEIGHBOR_ALLTOALLV = pmpix_neighbor_alltoallv_
#pragma weak mpix_neighbor_alltoallv__ = pmpix_neighbor_alltoallv_
#pragma weak mpix_neighbor_alltoallv_ = pmpix_neighbor_alltoallv_
#pragma weak mpix_neighbor_alltoallv = pmpix_neighbor_alltoallv_
#else
#pragma weak MPIX_NEIGHBOR_ALLTOALLV = pmpix_neighbor_alltoallv
#pragma weak mpix_neighbor_alltoallv__ = pmpix_neighbor_alltoallv
#pragma weak mpix_neighbor_alltoallv_ = pmpix_neighbor_alltoallv
#pragma weak mpix_neighbor_alltoallv = pmpix_neighbor_alltoallv
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_NEIGHBOR_ALLTOALLV( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPIX_NEIGHBOR_ALLTOALLV = PMPIX_NEIGHBOR_ALLTOALLV
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_neighbor_alltoallv__( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_neighbor_alltoallv__ = pmpix_neighbor_alltoallv__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_neighbor_alltoallv( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_neighbor_alltoallv = pmpix_neighbor_alltoallv
#else
extern FORT_DLL_SPEC void FORT_CALL mpix_neighbor_alltoallv_( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_neighbor_alltoallv_ = pmpix_neighbor_alltoallv_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPIX_NEIGHBOR_ALLTOALLV  MPIX_NEIGHBOR_ALLTOALLV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpix_neighbor_alltoallv__  mpix_neighbor_alltoallv__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpix_neighbor_alltoallv  mpix_neighbor_alltoallv
#else
#pragma _HP_SECONDARY_DEF pmpix_neighbor_alltoallv_  mpix_neighbor_alltoallv_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPIX_NEIGHBOR_ALLTOALLV as PMPIX_NEIGHBOR_ALLTOALLV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpix_neighbor_alltoallv__ as pmpix_neighbor_alltoallv__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpix_neighbor_alltoallv as pmpix_neighbor_alltoallv
#else
#pragma _CRI duplicate mpix_neighbor_alltoallv_ as pmpix_neighbor_alltoallv_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPIX_NEIGHBOR_ALLTOALLV( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_neighbor_alltoallv__( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_neighbor_alltoallv( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_neighbor_alltoallv_( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpix_neighbor_alltoallv__ = MPIX_NEIGHBOR_ALLTOALLV
#pragma weak mpix_neighbor_alltoallv_ = MPIX_NEIGHBOR_ALLTOALLV
#pragma weak mpix_neighbor_alltoallv = MPIX_NEIGHBOR_ALLTOALLV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_NEIGHBOR_ALLTOALLV = mpix_neighbor_alltoallv__
#pragma weak mpix_neighbor_alltoallv_ = mpix_neighbor_alltoallv__
#pragma weak mpix_neighbor_alltoallv = mpix_neighbor_alltoallv__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_NEIGHBOR_ALLTOALLV = mpix_neighbor_alltoallv_
#pragma weak mpix_neighbor_alltoallv__ = mpix_neighbor_alltoallv_
#pragma weak mpix_neighbor_alltoallv = mpix_neighbor_alltoallv_
#else
#pragma weak MPIX_NEIGHBOR_ALLTOALLV = mpix_neighbor_alltoallv
#pragma weak mpix_neighbor_alltoallv__ = mpix_neighbor_alltoallv
#pragma weak mpix_neighbor_alltoallv_ = mpix_neighbor_alltoallv
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPIX_NEIGHBOR_ALLTOALLV( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_neighbor_alltoallv__( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_neighbor_alltoallv_( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpix_neighbor_alltoallv( void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, void*, MPI_Fint [], MPI_Fint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpix_neighbor_alltoallv__ = PMPIX_NEIGHBOR_ALLTOALLV
#pragma weak pmpix_neighbor_alltoallv_ = PMPIX_NEIGHBOR_ALLTOALLV
#pragma weak pmpix_neighbor_alltoallv = PMPIX_NEIGHBOR_ALLTOALLV
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPIX_NEIGHBOR_ALLTOALLV = pmpix_neighbor_alltoallv__
#pragma weak pmpix_neighbor_alltoallv_ = pmpix_neighbor_alltoallv__
#pragma weak pmpix_neighbor_alltoallv = pmpix_neighbor_alltoallv__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPIX_NEIGHBOR_ALLTOALLV = pmpix_neighbor_alltoallv_
#pragma weak pmpix_neighbor_alltoallv__ = pmpix_neighbor_alltoallv_
#pragma weak pmpix_neighbor_alltoallv = pmpix_neighbor_alltoallv_
#else
#pragma weak PMPIX_NEIGHBOR_ALLTOALLV = pmpix_neighbor_alltoallv
#pragma weak pmpix_neighbor_alltoallv__ = pmpix_neighbor_alltoallv
#pragma weak pmpix_neighbor_alltoallv_ = pmpix_neighbor_alltoallv
#endif /* Test on name mapping */
#endif /* Use multiple pragma weak */

#ifdef F77_NAME_UPPER
#define mpix_neighbor_alltoallv_ PMPIX_NEIGHBOR_ALLTOALLV
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_neighbor_alltoallv_ pmpix_neighbor_alltoallv__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_neighbor_alltoallv_ pmpix_neighbor_alltoallv
#else
#define mpix_neighbor_alltoallv_ pmpix_neighbor_alltoallv_
#endif /* Test on name mapping */

/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPIX_Neighbor_alltoallv
#define MPIX_Neighbor_alltoallv PMPIX_Neighbor_alltoallv 

#else

#ifdef F77_NAME_UPPER
#define mpix_neighbor_alltoallv_ MPIX_NEIGHBOR_ALLTOALLV
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_neighbor_alltoallv_ mpix_neighbor_alltoallv__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_neighbor_alltoallv_ mpix_neighbor_alltoallv
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpix_neighbor_alltoallv_ ( void*v1, MPI_Fint v2[], MPI_Fint v3[], MPI_Fint *v4, void*v5, MPI_Fint v6[], MPI_Fint v7[], MPI_Fint *v8, MPI_Fint *v9, MPI_Fint *ierr ){
    *ierr = MPIX_Neighbor_alltoallv( v1, v2, v3, (MPI_Datatype)(*v4), v5, v6, v7, (MPI_Datatype)(*v8), (MPI_Comm)(*v9) );
}
