/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_RACCUMULATE( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_raccumulate__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_raccumulate( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_raccumulate_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPIX_RACCUMULATE = PMPIX_RACCUMULATE
#pragma weak mpix_raccumulate__ = PMPIX_RACCUMULATE
#pragma weak mpix_raccumulate_ = PMPIX_RACCUMULATE
#pragma weak mpix_raccumulate = PMPIX_RACCUMULATE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_RACCUMULATE = pmpix_raccumulate__
#pragma weak mpix_raccumulate__ = pmpix_raccumulate__
#pragma weak mpix_raccumulate_ = pmpix_raccumulate__
#pragma weak mpix_raccumulate = pmpix_raccumulate__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_RACCUMULATE = pmpix_raccumulate_
#pragma weak mpix_raccumulate__ = pmpix_raccumulate_
#pragma weak mpix_raccumulate_ = pmpix_raccumulate_
#pragma weak mpix_raccumulate = pmpix_raccumulate_
#else
#pragma weak MPIX_RACCUMULATE = pmpix_raccumulate
#pragma weak mpix_raccumulate__ = pmpix_raccumulate
#pragma weak mpix_raccumulate_ = pmpix_raccumulate
#pragma weak mpix_raccumulate = pmpix_raccumulate
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_RACCUMULATE( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPIX_RACCUMULATE = PMPIX_RACCUMULATE
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_raccumulate__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_raccumulate__ = pmpix_raccumulate__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_raccumulate( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_raccumulate = pmpix_raccumulate
#else
extern FORT_DLL_SPEC void FORT_CALL mpix_raccumulate_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_raccumulate_ = pmpix_raccumulate_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPIX_RACCUMULATE  MPIX_RACCUMULATE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpix_raccumulate__  mpix_raccumulate__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpix_raccumulate  mpix_raccumulate
#else
#pragma _HP_SECONDARY_DEF pmpix_raccumulate_  mpix_raccumulate_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPIX_RACCUMULATE as PMPIX_RACCUMULATE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpix_raccumulate__ as pmpix_raccumulate__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpix_raccumulate as pmpix_raccumulate
#else
#pragma _CRI duplicate mpix_raccumulate_ as pmpix_raccumulate_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPIX_RACCUMULATE( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_raccumulate__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_raccumulate( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_raccumulate_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpix_raccumulate__ = MPIX_RACCUMULATE
#pragma weak mpix_raccumulate_ = MPIX_RACCUMULATE
#pragma weak mpix_raccumulate = MPIX_RACCUMULATE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_RACCUMULATE = mpix_raccumulate__
#pragma weak mpix_raccumulate_ = mpix_raccumulate__
#pragma weak mpix_raccumulate = mpix_raccumulate__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_RACCUMULATE = mpix_raccumulate_
#pragma weak mpix_raccumulate__ = mpix_raccumulate_
#pragma weak mpix_raccumulate = mpix_raccumulate_
#else
#pragma weak MPIX_RACCUMULATE = mpix_raccumulate
#pragma weak mpix_raccumulate__ = mpix_raccumulate
#pragma weak mpix_raccumulate_ = mpix_raccumulate
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPIX_RACCUMULATE( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_raccumulate__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_raccumulate_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpix_raccumulate( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpix_raccumulate__ = PMPIX_RACCUMULATE
#pragma weak pmpix_raccumulate_ = PMPIX_RACCUMULATE
#pragma weak pmpix_raccumulate = PMPIX_RACCUMULATE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPIX_RACCUMULATE = pmpix_raccumulate__
#pragma weak pmpix_raccumulate_ = pmpix_raccumulate__
#pragma weak pmpix_raccumulate = pmpix_raccumulate__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPIX_RACCUMULATE = pmpix_raccumulate_
#pragma weak pmpix_raccumulate__ = pmpix_raccumulate_
#pragma weak pmpix_raccumulate = pmpix_raccumulate_
#else
#pragma weak PMPIX_RACCUMULATE = pmpix_raccumulate
#pragma weak pmpix_raccumulate__ = pmpix_raccumulate
#pragma weak pmpix_raccumulate_ = pmpix_raccumulate
#endif /* Test on name mapping */
#endif /* Use multiple pragma weak */

#ifdef F77_NAME_UPPER
#define mpix_raccumulate_ PMPIX_RACCUMULATE
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_raccumulate_ pmpix_raccumulate__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_raccumulate_ pmpix_raccumulate
#else
#define mpix_raccumulate_ pmpix_raccumulate_
#endif /* Test on name mapping */

/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPIX_Raccumulate
#define MPIX_Raccumulate PMPIX_Raccumulate 

#else

#ifdef F77_NAME_UPPER
#define mpix_raccumulate_ MPIX_RACCUMULATE
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_raccumulate_ mpix_raccumulate__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_raccumulate_ mpix_raccumulate
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpix_raccumulate_ ( void*v1, MPI_Fint *v2, MPI_Fint *v3, MPI_Fint *v4, MPI_Fint *v5, MPI_Fint *v6, MPI_Fint *v7, MPI_Fint *v8, MPI_Fint *v9, MPI_Fint *v10, MPI_Fint *ierr ){
    *ierr = MPIX_Raccumulate( v1, *v2, (MPI_Datatype)(*v3), *v4, *v5, *v6, (MPI_Datatype)(*v7), *v8, *v9, (MPI_Request *)(v10) );
}
