/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_RPUT( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_rput__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_rput( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_rput_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPIX_RPUT = PMPIX_RPUT
#pragma weak mpix_rput__ = PMPIX_RPUT
#pragma weak mpix_rput_ = PMPIX_RPUT
#pragma weak mpix_rput = PMPIX_RPUT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_RPUT = pmpix_rput__
#pragma weak mpix_rput__ = pmpix_rput__
#pragma weak mpix_rput_ = pmpix_rput__
#pragma weak mpix_rput = pmpix_rput__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_RPUT = pmpix_rput_
#pragma weak mpix_rput__ = pmpix_rput_
#pragma weak mpix_rput_ = pmpix_rput_
#pragma weak mpix_rput = pmpix_rput_
#else
#pragma weak MPIX_RPUT = pmpix_rput
#pragma weak mpix_rput__ = pmpix_rput
#pragma weak mpix_rput_ = pmpix_rput
#pragma weak mpix_rput = pmpix_rput
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_RPUT( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPIX_RPUT = PMPIX_RPUT
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_rput__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_rput__ = pmpix_rput__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_rput( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_rput = pmpix_rput
#else
extern FORT_DLL_SPEC void FORT_CALL mpix_rput_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_rput_ = pmpix_rput_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPIX_RPUT  MPIX_RPUT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpix_rput__  mpix_rput__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpix_rput  mpix_rput
#else
#pragma _HP_SECONDARY_DEF pmpix_rput_  mpix_rput_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPIX_RPUT as PMPIX_RPUT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpix_rput__ as pmpix_rput__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpix_rput as pmpix_rput
#else
#pragma _CRI duplicate mpix_rput_ as pmpix_rput_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPIX_RPUT( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_rput__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_rput( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_rput_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpix_rput__ = MPIX_RPUT
#pragma weak mpix_rput_ = MPIX_RPUT
#pragma weak mpix_rput = MPIX_RPUT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_RPUT = mpix_rput__
#pragma weak mpix_rput_ = mpix_rput__
#pragma weak mpix_rput = mpix_rput__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_RPUT = mpix_rput_
#pragma weak mpix_rput__ = mpix_rput_
#pragma weak mpix_rput = mpix_rput_
#else
#pragma weak MPIX_RPUT = mpix_rput
#pragma weak mpix_rput__ = mpix_rput
#pragma weak mpix_rput_ = mpix_rput
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPIX_RPUT( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_rput__( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_rput_( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpix_rput( void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpix_rput__ = PMPIX_RPUT
#pragma weak pmpix_rput_ = PMPIX_RPUT
#pragma weak pmpix_rput = PMPIX_RPUT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPIX_RPUT = pmpix_rput__
#pragma weak pmpix_rput_ = pmpix_rput__
#pragma weak pmpix_rput = pmpix_rput__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPIX_RPUT = pmpix_rput_
#pragma weak pmpix_rput__ = pmpix_rput_
#pragma weak pmpix_rput = pmpix_rput_
#else
#pragma weak PMPIX_RPUT = pmpix_rput
#pragma weak pmpix_rput__ = pmpix_rput
#pragma weak pmpix_rput_ = pmpix_rput
#endif /* Test on name mapping */
#endif /* Use multiple pragma weak */

#ifdef F77_NAME_UPPER
#define mpix_rput_ PMPIX_RPUT
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_rput_ pmpix_rput__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_rput_ pmpix_rput
#else
#define mpix_rput_ pmpix_rput_
#endif /* Test on name mapping */

/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPIX_Rput
#define MPIX_Rput PMPIX_Rput 

#else

#ifdef F77_NAME_UPPER
#define mpix_rput_ MPIX_RPUT
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_rput_ mpix_rput__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_rput_ mpix_rput
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpix_rput_ ( void*v1, MPI_Fint *v2, MPI_Fint *v3, MPI_Fint *v4, MPI_Fint *v5, MPI_Fint *v6, MPI_Fint *v7, MPI_Fint *v8, MPI_Fint *v9, MPI_Fint *ierr ){
    *ierr = MPIX_Rput( v1, *v2, (MPI_Datatype)(*v3), *v4, *v5, *v6, (MPI_Datatype)(*v7), *v8, (MPI_Request *)(v9) );
}
