/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_TYPE_CREATE_HINDEXED_BLOCK( MPI_Fint *, MPI_Fint *, MPI_Aint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_type_create_hindexed_block__( MPI_Fint *, MPI_Fint *, MPI_Aint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_type_create_hindexed_block( MPI_Fint *, MPI_Fint *, MPI_Aint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_type_create_hindexed_block_( MPI_Fint *, MPI_Fint *, MPI_Aint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPIX_TYPE_CREATE_HINDEXED_BLOCK = PMPIX_TYPE_CREATE_HINDEXED_BLOCK
#pragma weak mpix_type_create_hindexed_block__ = PMPIX_TYPE_CREATE_HINDEXED_BLOCK
#pragma weak mpix_type_create_hindexed_block_ = PMPIX_TYPE_CREATE_HINDEXED_BLOCK
#pragma weak mpix_type_create_hindexed_block = PMPIX_TYPE_CREATE_HINDEXED_BLOCK
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_TYPE_CREATE_HINDEXED_BLOCK = pmpix_type_create_hindexed_block__
#pragma weak mpix_type_create_hindexed_block__ = pmpix_type_create_hindexed_block__
#pragma weak mpix_type_create_hindexed_block_ = pmpix_type_create_hindexed_block__
#pragma weak mpix_type_create_hindexed_block = pmpix_type_create_hindexed_block__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_TYPE_CREATE_HINDEXED_BLOCK = pmpix_type_create_hindexed_block_
#pragma weak mpix_type_create_hindexed_block__ = pmpix_type_create_hindexed_block_
#pragma weak mpix_type_create_hindexed_block_ = pmpix_type_create_hindexed_block_
#pragma weak mpix_type_create_hindexed_block = pmpix_type_create_hindexed_block_
#else
#pragma weak MPIX_TYPE_CREATE_HINDEXED_BLOCK = pmpix_type_create_hindexed_block
#pragma weak mpix_type_create_hindexed_block__ = pmpix_type_create_hindexed_block
#pragma weak mpix_type_create_hindexed_block_ = pmpix_type_create_hindexed_block
#pragma weak mpix_type_create_hindexed_block = pmpix_type_create_hindexed_block
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_TYPE_CREATE_HINDEXED_BLOCK( MPI_Fint *, MPI_Fint *, MPI_Aint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPIX_TYPE_CREATE_HINDEXED_BLOCK = PMPIX_TYPE_CREATE_HINDEXED_BLOCK
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_type_create_hindexed_block__( MPI_Fint *, MPI_Fint *, MPI_Aint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_type_create_hindexed_block__ = pmpix_type_create_hindexed_block__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_type_create_hindexed_block( MPI_Fint *, MPI_Fint *, MPI_Aint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_type_create_hindexed_block = pmpix_type_create_hindexed_block
#else
extern FORT_DLL_SPEC void FORT_CALL mpix_type_create_hindexed_block_( MPI_Fint *, MPI_Fint *, MPI_Aint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_type_create_hindexed_block_ = pmpix_type_create_hindexed_block_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPIX_TYPE_CREATE_HINDEXED_BLOCK  MPIX_TYPE_CREATE_HINDEXED_BLOCK
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpix_type_create_hindexed_block__  mpix_type_create_hindexed_block__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpix_type_create_hindexed_block  mpix_type_create_hindexed_block
#else
#pragma _HP_SECONDARY_DEF pmpix_type_create_hindexed_block_  mpix_type_create_hindexed_block_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPIX_TYPE_CREATE_HINDEXED_BLOCK as PMPIX_TYPE_CREATE_HINDEXED_BLOCK
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpix_type_create_hindexed_block__ as pmpix_type_create_hindexed_block__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpix_type_create_hindexed_block as pmpix_type_create_hindexed_block
#else
#pragma _CRI duplicate mpix_type_create_hindexed_block_ as pmpix_type_create_hindexed_block_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPIX_TYPE_CREATE_HINDEXED_BLOCK( MPI_Fint *, MPI_Fint *, MPI_Aint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_type_create_hindexed_block__( MPI_Fint *, MPI_Fint *, MPI_Aint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_type_create_hindexed_block( MPI_Fint *, MPI_Fint *, MPI_Aint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_type_create_hindexed_block_( MPI_Fint *, MPI_Fint *, MPI_Aint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpix_type_create_hindexed_block__ = MPIX_TYPE_CREATE_HINDEXED_BLOCK
#pragma weak mpix_type_create_hindexed_block_ = MPIX_TYPE_CREATE_HINDEXED_BLOCK
#pragma weak mpix_type_create_hindexed_block = MPIX_TYPE_CREATE_HINDEXED_BLOCK
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_TYPE_CREATE_HINDEXED_BLOCK = mpix_type_create_hindexed_block__
#pragma weak mpix_type_create_hindexed_block_ = mpix_type_create_hindexed_block__
#pragma weak mpix_type_create_hindexed_block = mpix_type_create_hindexed_block__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_TYPE_CREATE_HINDEXED_BLOCK = mpix_type_create_hindexed_block_
#pragma weak mpix_type_create_hindexed_block__ = mpix_type_create_hindexed_block_
#pragma weak mpix_type_create_hindexed_block = mpix_type_create_hindexed_block_
#else
#pragma weak MPIX_TYPE_CREATE_HINDEXED_BLOCK = mpix_type_create_hindexed_block
#pragma weak mpix_type_create_hindexed_block__ = mpix_type_create_hindexed_block
#pragma weak mpix_type_create_hindexed_block_ = mpix_type_create_hindexed_block
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPIX_TYPE_CREATE_HINDEXED_BLOCK( MPI_Fint *, MPI_Fint *, MPI_Aint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_type_create_hindexed_block__( MPI_Fint *, MPI_Fint *, MPI_Aint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_type_create_hindexed_block_( MPI_Fint *, MPI_Fint *, MPI_Aint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpix_type_create_hindexed_block( MPI_Fint *, MPI_Fint *, MPI_Aint [], MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpix_type_create_hindexed_block__ = PMPIX_TYPE_CREATE_HINDEXED_BLOCK
#pragma weak pmpix_type_create_hindexed_block_ = PMPIX_TYPE_CREATE_HINDEXED_BLOCK
#pragma weak pmpix_type_create_hindexed_block = PMPIX_TYPE_CREATE_HINDEXED_BLOCK
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPIX_TYPE_CREATE_HINDEXED_BLOCK = pmpix_type_create_hindexed_block__
#pragma weak pmpix_type_create_hindexed_block_ = pmpix_type_create_hindexed_block__
#pragma weak pmpix_type_create_hindexed_block = pmpix_type_create_hindexed_block__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPIX_TYPE_CREATE_HINDEXED_BLOCK = pmpix_type_create_hindexed_block_
#pragma weak pmpix_type_create_hindexed_block__ = pmpix_type_create_hindexed_block_
#pragma weak pmpix_type_create_hindexed_block = pmpix_type_create_hindexed_block_
#else
#pragma weak PMPIX_TYPE_CREATE_HINDEXED_BLOCK = pmpix_type_create_hindexed_block
#pragma weak pmpix_type_create_hindexed_block__ = pmpix_type_create_hindexed_block
#pragma weak pmpix_type_create_hindexed_block_ = pmpix_type_create_hindexed_block
#endif /* Test on name mapping */
#endif /* Use multiple pragma weak */

#ifdef F77_NAME_UPPER
#define mpix_type_create_hindexed_block_ PMPIX_TYPE_CREATE_HINDEXED_BLOCK
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_type_create_hindexed_block_ pmpix_type_create_hindexed_block__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_type_create_hindexed_block_ pmpix_type_create_hindexed_block
#else
#define mpix_type_create_hindexed_block_ pmpix_type_create_hindexed_block_
#endif /* Test on name mapping */

/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPIX_Type_create_hindexed_block
#define MPIX_Type_create_hindexed_block PMPIX_Type_create_hindexed_block 

#else

#ifdef F77_NAME_UPPER
#define mpix_type_create_hindexed_block_ MPIX_TYPE_CREATE_HINDEXED_BLOCK
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_type_create_hindexed_block_ mpix_type_create_hindexed_block__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_type_create_hindexed_block_ mpix_type_create_hindexed_block
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpix_type_create_hindexed_block_ ( MPI_Fint *v1, MPI_Fint *v2, MPI_Aint v3[], MPI_Fint *v4, MPI_Fint *v5, MPI_Fint *ierr ){
    *ierr = MPIX_Type_create_hindexed_block( *v1, *v2, v3, (MPI_Datatype)(*v4), (MPI_Datatype *)(v5) );
}
