/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_WIN_CREATE_DYNAMIC( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_win_create_dynamic__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_win_create_dynamic( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_win_create_dynamic_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPIX_WIN_CREATE_DYNAMIC = PMPIX_WIN_CREATE_DYNAMIC
#pragma weak mpix_win_create_dynamic__ = PMPIX_WIN_CREATE_DYNAMIC
#pragma weak mpix_win_create_dynamic_ = PMPIX_WIN_CREATE_DYNAMIC
#pragma weak mpix_win_create_dynamic = PMPIX_WIN_CREATE_DYNAMIC
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_WIN_CREATE_DYNAMIC = pmpix_win_create_dynamic__
#pragma weak mpix_win_create_dynamic__ = pmpix_win_create_dynamic__
#pragma weak mpix_win_create_dynamic_ = pmpix_win_create_dynamic__
#pragma weak mpix_win_create_dynamic = pmpix_win_create_dynamic__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_WIN_CREATE_DYNAMIC = pmpix_win_create_dynamic_
#pragma weak mpix_win_create_dynamic__ = pmpix_win_create_dynamic_
#pragma weak mpix_win_create_dynamic_ = pmpix_win_create_dynamic_
#pragma weak mpix_win_create_dynamic = pmpix_win_create_dynamic_
#else
#pragma weak MPIX_WIN_CREATE_DYNAMIC = pmpix_win_create_dynamic
#pragma weak mpix_win_create_dynamic__ = pmpix_win_create_dynamic
#pragma weak mpix_win_create_dynamic_ = pmpix_win_create_dynamic
#pragma weak mpix_win_create_dynamic = pmpix_win_create_dynamic
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_WIN_CREATE_DYNAMIC( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPIX_WIN_CREATE_DYNAMIC = PMPIX_WIN_CREATE_DYNAMIC
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_win_create_dynamic__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_win_create_dynamic__ = pmpix_win_create_dynamic__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_win_create_dynamic( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_win_create_dynamic = pmpix_win_create_dynamic
#else
extern FORT_DLL_SPEC void FORT_CALL mpix_win_create_dynamic_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_win_create_dynamic_ = pmpix_win_create_dynamic_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPIX_WIN_CREATE_DYNAMIC  MPIX_WIN_CREATE_DYNAMIC
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpix_win_create_dynamic__  mpix_win_create_dynamic__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpix_win_create_dynamic  mpix_win_create_dynamic
#else
#pragma _HP_SECONDARY_DEF pmpix_win_create_dynamic_  mpix_win_create_dynamic_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPIX_WIN_CREATE_DYNAMIC as PMPIX_WIN_CREATE_DYNAMIC
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpix_win_create_dynamic__ as pmpix_win_create_dynamic__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpix_win_create_dynamic as pmpix_win_create_dynamic
#else
#pragma _CRI duplicate mpix_win_create_dynamic_ as pmpix_win_create_dynamic_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPIX_WIN_CREATE_DYNAMIC( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_win_create_dynamic__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_win_create_dynamic( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_win_create_dynamic_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpix_win_create_dynamic__ = MPIX_WIN_CREATE_DYNAMIC
#pragma weak mpix_win_create_dynamic_ = MPIX_WIN_CREATE_DYNAMIC
#pragma weak mpix_win_create_dynamic = MPIX_WIN_CREATE_DYNAMIC
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_WIN_CREATE_DYNAMIC = mpix_win_create_dynamic__
#pragma weak mpix_win_create_dynamic_ = mpix_win_create_dynamic__
#pragma weak mpix_win_create_dynamic = mpix_win_create_dynamic__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_WIN_CREATE_DYNAMIC = mpix_win_create_dynamic_
#pragma weak mpix_win_create_dynamic__ = mpix_win_create_dynamic_
#pragma weak mpix_win_create_dynamic = mpix_win_create_dynamic_
#else
#pragma weak MPIX_WIN_CREATE_DYNAMIC = mpix_win_create_dynamic
#pragma weak mpix_win_create_dynamic__ = mpix_win_create_dynamic
#pragma weak mpix_win_create_dynamic_ = mpix_win_create_dynamic
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPIX_WIN_CREATE_DYNAMIC( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_win_create_dynamic__( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_win_create_dynamic_( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpix_win_create_dynamic( MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpix_win_create_dynamic__ = PMPIX_WIN_CREATE_DYNAMIC
#pragma weak pmpix_win_create_dynamic_ = PMPIX_WIN_CREATE_DYNAMIC
#pragma weak pmpix_win_create_dynamic = PMPIX_WIN_CREATE_DYNAMIC
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPIX_WIN_CREATE_DYNAMIC = pmpix_win_create_dynamic__
#pragma weak pmpix_win_create_dynamic_ = pmpix_win_create_dynamic__
#pragma weak pmpix_win_create_dynamic = pmpix_win_create_dynamic__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPIX_WIN_CREATE_DYNAMIC = pmpix_win_create_dynamic_
#pragma weak pmpix_win_create_dynamic__ = pmpix_win_create_dynamic_
#pragma weak pmpix_win_create_dynamic = pmpix_win_create_dynamic_
#else
#pragma weak PMPIX_WIN_CREATE_DYNAMIC = pmpix_win_create_dynamic
#pragma weak pmpix_win_create_dynamic__ = pmpix_win_create_dynamic
#pragma weak pmpix_win_create_dynamic_ = pmpix_win_create_dynamic
#endif /* Test on name mapping */
#endif /* Use multiple pragma weak */

#ifdef F77_NAME_UPPER
#define mpix_win_create_dynamic_ PMPIX_WIN_CREATE_DYNAMIC
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_win_create_dynamic_ pmpix_win_create_dynamic__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_win_create_dynamic_ pmpix_win_create_dynamic
#else
#define mpix_win_create_dynamic_ pmpix_win_create_dynamic_
#endif /* Test on name mapping */

/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPIX_Win_create_dynamic
#define MPIX_Win_create_dynamic PMPIX_Win_create_dynamic 

#else

#ifdef F77_NAME_UPPER
#define mpix_win_create_dynamic_ MPIX_WIN_CREATE_DYNAMIC
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_win_create_dynamic_ mpix_win_create_dynamic__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_win_create_dynamic_ mpix_win_create_dynamic
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpix_win_create_dynamic_ ( MPI_Fint *v1, MPI_Fint *v2, MPI_Fint *v3, MPI_Fint *ierr ){
    *ierr = MPIX_Win_create_dynamic( (MPI_Info)(*v1), (MPI_Comm)(*v2), v3 );
}
