/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_WIN_ATTACH( MPI_Fint *, void*, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_win_attach__( MPI_Fint *, void*, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_win_attach( MPI_Fint *, void*, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_win_attach_( MPI_Fint *, void*, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPIX_WIN_ATTACH = PMPIX_WIN_ATTACH
#pragma weak mpix_win_attach__ = PMPIX_WIN_ATTACH
#pragma weak mpix_win_attach_ = PMPIX_WIN_ATTACH
#pragma weak mpix_win_attach = PMPIX_WIN_ATTACH
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_WIN_ATTACH = pmpix_win_attach__
#pragma weak mpix_win_attach__ = pmpix_win_attach__
#pragma weak mpix_win_attach_ = pmpix_win_attach__
#pragma weak mpix_win_attach = pmpix_win_attach__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_WIN_ATTACH = pmpix_win_attach_
#pragma weak mpix_win_attach__ = pmpix_win_attach_
#pragma weak mpix_win_attach_ = pmpix_win_attach_
#pragma weak mpix_win_attach = pmpix_win_attach_
#else
#pragma weak MPIX_WIN_ATTACH = pmpix_win_attach
#pragma weak mpix_win_attach__ = pmpix_win_attach
#pragma weak mpix_win_attach_ = pmpix_win_attach
#pragma weak mpix_win_attach = pmpix_win_attach
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_WIN_ATTACH( MPI_Fint *, void*, MPI_Fint *, MPI_Fint * );

#pragma weak MPIX_WIN_ATTACH = PMPIX_WIN_ATTACH
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_win_attach__( MPI_Fint *, void*, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_win_attach__ = pmpix_win_attach__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_win_attach( MPI_Fint *, void*, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_win_attach = pmpix_win_attach
#else
extern FORT_DLL_SPEC void FORT_CALL mpix_win_attach_( MPI_Fint *, void*, MPI_Fint *, MPI_Fint * );

#pragma weak mpix_win_attach_ = pmpix_win_attach_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPIX_WIN_ATTACH  MPIX_WIN_ATTACH
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpix_win_attach__  mpix_win_attach__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpix_win_attach  mpix_win_attach
#else
#pragma _HP_SECONDARY_DEF pmpix_win_attach_  mpix_win_attach_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPIX_WIN_ATTACH as PMPIX_WIN_ATTACH
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpix_win_attach__ as pmpix_win_attach__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpix_win_attach as pmpix_win_attach
#else
#pragma _CRI duplicate mpix_win_attach_ as pmpix_win_attach_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPIX_WIN_ATTACH( MPI_Fint *, void*, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_win_attach__( MPI_Fint *, void*, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_win_attach( MPI_Fint *, void*, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_win_attach_( MPI_Fint *, void*, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpix_win_attach__ = MPIX_WIN_ATTACH
#pragma weak mpix_win_attach_ = MPIX_WIN_ATTACH
#pragma weak mpix_win_attach = MPIX_WIN_ATTACH
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_WIN_ATTACH = mpix_win_attach__
#pragma weak mpix_win_attach_ = mpix_win_attach__
#pragma weak mpix_win_attach = mpix_win_attach__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_WIN_ATTACH = mpix_win_attach_
#pragma weak mpix_win_attach__ = mpix_win_attach_
#pragma weak mpix_win_attach = mpix_win_attach_
#else
#pragma weak MPIX_WIN_ATTACH = mpix_win_attach
#pragma weak mpix_win_attach__ = mpix_win_attach
#pragma weak mpix_win_attach_ = mpix_win_attach
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPIX_WIN_ATTACH( MPI_Fint *, void*, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_win_attach__( MPI_Fint *, void*, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_win_attach_( MPI_Fint *, void*, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpix_win_attach( MPI_Fint *, void*, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpix_win_attach__ = PMPIX_WIN_ATTACH
#pragma weak pmpix_win_attach_ = PMPIX_WIN_ATTACH
#pragma weak pmpix_win_attach = PMPIX_WIN_ATTACH
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPIX_WIN_ATTACH = pmpix_win_attach__
#pragma weak pmpix_win_attach_ = pmpix_win_attach__
#pragma weak pmpix_win_attach = pmpix_win_attach__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPIX_WIN_ATTACH = pmpix_win_attach_
#pragma weak pmpix_win_attach__ = pmpix_win_attach_
#pragma weak pmpix_win_attach = pmpix_win_attach_
#else
#pragma weak PMPIX_WIN_ATTACH = pmpix_win_attach
#pragma weak pmpix_win_attach__ = pmpix_win_attach
#pragma weak pmpix_win_attach_ = pmpix_win_attach
#endif /* Test on name mapping */
#endif /* Use multiple pragma weak */

#ifdef F77_NAME_UPPER
#define mpix_win_attach_ PMPIX_WIN_ATTACH
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_win_attach_ pmpix_win_attach__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_win_attach_ pmpix_win_attach
#else
#define mpix_win_attach_ pmpix_win_attach_
#endif /* Test on name mapping */

/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPIX_Win_attach
#define MPIX_Win_attach PMPIX_Win_attach 

#else

#ifdef F77_NAME_UPPER
#define mpix_win_attach_ MPIX_WIN_ATTACH
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_win_attach_ mpix_win_attach__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_win_attach_ mpix_win_attach
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpix_win_attach_ ( MPI_Fint *v1, void*v2, MPI_Fint *v3, MPI_Fint *ierr ){
    *ierr = MPIX_Win_attach( *v1, v2, *v3 );
}
