/*
 * Copyright (C) by Argonne National Laboratory
 *     See COPYRIGHT in top-level directory
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_QUERY_CUDA_SUPPORT( MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support__( MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support( MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support_( MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPIX_QUERY_CUDA_SUPPORT = PMPIX_QUERY_CUDA_SUPPORT
#pragma weak mpix_query_cuda_support__ = PMPIX_QUERY_CUDA_SUPPORT
#pragma weak mpix_query_cuda_support_ = PMPIX_QUERY_CUDA_SUPPORT
#pragma weak mpix_query_cuda_support = PMPIX_QUERY_CUDA_SUPPORT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_QUERY_CUDA_SUPPORT = pmpix_query_cuda_support__
#pragma weak mpix_query_cuda_support__ = pmpix_query_cuda_support__
#pragma weak mpix_query_cuda_support_ = pmpix_query_cuda_support__
#pragma weak mpix_query_cuda_support = pmpix_query_cuda_support__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_QUERY_CUDA_SUPPORT = pmpix_query_cuda_support_
#pragma weak mpix_query_cuda_support__ = pmpix_query_cuda_support_
#pragma weak mpix_query_cuda_support_ = pmpix_query_cuda_support_
#pragma weak mpix_query_cuda_support = pmpix_query_cuda_support_
#else
#pragma weak MPIX_QUERY_CUDA_SUPPORT = pmpix_query_cuda_support
#pragma weak mpix_query_cuda_support__ = pmpix_query_cuda_support
#pragma weak mpix_query_cuda_support_ = pmpix_query_cuda_support
#pragma weak mpix_query_cuda_support = pmpix_query_cuda_support
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_QUERY_CUDA_SUPPORT( MPI_Fint * );

#pragma weak MPIX_QUERY_CUDA_SUPPORT = PMPIX_QUERY_CUDA_SUPPORT
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support__( MPI_Fint * );

#pragma weak mpix_query_cuda_support__ = pmpix_query_cuda_support__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support( MPI_Fint * );

#pragma weak mpix_query_cuda_support = pmpix_query_cuda_support
#else
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support_( MPI_Fint * );

#pragma weak mpix_query_cuda_support_ = pmpix_query_cuda_support_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPIX_QUERY_CUDA_SUPPORT  MPIX_QUERY_CUDA_SUPPORT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpix_query_cuda_support__  mpix_query_cuda_support__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpix_query_cuda_support  mpix_query_cuda_support
#else
#pragma _HP_SECONDARY_DEF pmpix_query_cuda_support_  mpix_query_cuda_support_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPIX_QUERY_CUDA_SUPPORT as PMPIX_QUERY_CUDA_SUPPORT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpix_query_cuda_support__ as pmpix_query_cuda_support__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpix_query_cuda_support as pmpix_query_cuda_support
#else
#pragma _CRI duplicate mpix_query_cuda_support_ as pmpix_query_cuda_support_
#endif

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_QUERY_CUDA_SUPPORT( MPI_Fint * ) __attribute__((weak,alias("PMPIX_QUERY_CUDA_SUPPORT")));
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support__( MPI_Fint * ) __attribute__((weak,alias("PMPIX_QUERY_CUDA_SUPPORT")));
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support_( MPI_Fint * ) __attribute__((weak,alias("PMPIX_QUERY_CUDA_SUPPORT")));
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support( MPI_Fint * ) __attribute__((weak,alias("PMPIX_QUERY_CUDA_SUPPORT")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPIX_QUERY_CUDA_SUPPORT( MPI_Fint * ) __attribute__((weak,alias("pmpix_query_cuda_support__")));
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support__( MPI_Fint * ) __attribute__((weak,alias("pmpix_query_cuda_support__")));
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support_( MPI_Fint * ) __attribute__((weak,alias("pmpix_query_cuda_support__")));
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support( MPI_Fint * ) __attribute__((weak,alias("pmpix_query_cuda_support__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPIX_QUERY_CUDA_SUPPORT( MPI_Fint * ) __attribute__((weak,alias("pmpix_query_cuda_support_")));
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support__( MPI_Fint * ) __attribute__((weak,alias("pmpix_query_cuda_support_")));
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support_( MPI_Fint * ) __attribute__((weak,alias("pmpix_query_cuda_support_")));
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support( MPI_Fint * ) __attribute__((weak,alias("pmpix_query_cuda_support_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPIX_QUERY_CUDA_SUPPORT( MPI_Fint * ) __attribute__((weak,alias("pmpix_query_cuda_support")));
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support__( MPI_Fint * ) __attribute__((weak,alias("pmpix_query_cuda_support")));
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support_( MPI_Fint * ) __attribute__((weak,alias("pmpix_query_cuda_support")));
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support( MPI_Fint * ) __attribute__((weak,alias("pmpix_query_cuda_support")));

#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(USE_ONLY_MPI_NAMES)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPIX_QUERY_CUDA_SUPPORT( MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support__( MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support( MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support_( MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpix_query_cuda_support__ = MPIX_QUERY_CUDA_SUPPORT
#pragma weak mpix_query_cuda_support_ = MPIX_QUERY_CUDA_SUPPORT
#pragma weak mpix_query_cuda_support = MPIX_QUERY_CUDA_SUPPORT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPIX_QUERY_CUDA_SUPPORT = mpix_query_cuda_support__
#pragma weak mpix_query_cuda_support_ = mpix_query_cuda_support__
#pragma weak mpix_query_cuda_support = mpix_query_cuda_support__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPIX_QUERY_CUDA_SUPPORT = mpix_query_cuda_support_
#pragma weak mpix_query_cuda_support__ = mpix_query_cuda_support_
#pragma weak mpix_query_cuda_support = mpix_query_cuda_support_
#else
#pragma weak MPIX_QUERY_CUDA_SUPPORT = mpix_query_cuda_support
#pragma weak mpix_query_cuda_support__ = mpix_query_cuda_support
#pragma weak mpix_query_cuda_support_ = mpix_query_cuda_support
#endif
#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPIX_QUERY_CUDA_SUPPORT( MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support__( MPI_Fint * ) __attribute__((weak,alias("MPIX_QUERY_CUDA_SUPPORT")));
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support_( MPI_Fint * ) __attribute__((weak,alias("MPIX_QUERY_CUDA_SUPPORT")));
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support( MPI_Fint * ) __attribute__((weak,alias("MPIX_QUERY_CUDA_SUPPORT")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPIX_QUERY_CUDA_SUPPORT( MPI_Fint * ) __attribute__((weak,alias("mpix_query_cuda_support__")));
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support__( MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support_( MPI_Fint * ) __attribute__((weak,alias("mpix_query_cuda_support__")));
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support( MPI_Fint * ) __attribute__((weak,alias("mpix_query_cuda_support__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL MPIX_QUERY_CUDA_SUPPORT( MPI_Fint * ) __attribute__((weak,alias("mpix_query_cuda_support_")));
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support__( MPI_Fint * ) __attribute__((weak,alias("mpix_query_cuda_support_")));
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support_( MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support( MPI_Fint * ) __attribute__((weak,alias("mpix_query_cuda_support_")));

#else
extern FORT_DLL_SPEC void FORT_CALL MPIX_QUERY_CUDA_SUPPORT( MPI_Fint * ) __attribute__((weak,alias("mpix_query_cuda_support")));
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support__( MPI_Fint * ) __attribute__((weak,alias("mpix_query_cuda_support")));
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support_( MPI_Fint * ) __attribute__((weak,alias("mpix_query_cuda_support")));
extern FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support( MPI_Fint * );

#endif
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS)
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPIX_QUERY_CUDA_SUPPORT( MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_query_cuda_support__( MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpix_query_cuda_support_( MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpix_query_cuda_support( MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpix_query_cuda_support__ = PMPIX_QUERY_CUDA_SUPPORT
#pragma weak pmpix_query_cuda_support_ = PMPIX_QUERY_CUDA_SUPPORT
#pragma weak pmpix_query_cuda_support = PMPIX_QUERY_CUDA_SUPPORT
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPIX_QUERY_CUDA_SUPPORT = pmpix_query_cuda_support__
#pragma weak pmpix_query_cuda_support_ = pmpix_query_cuda_support__
#pragma weak pmpix_query_cuda_support = pmpix_query_cuda_support__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPIX_QUERY_CUDA_SUPPORT = pmpix_query_cuda_support_
#pragma weak pmpix_query_cuda_support__ = pmpix_query_cuda_support_
#pragma weak pmpix_query_cuda_support = pmpix_query_cuda_support_
#else
#pragma weak PMPIX_QUERY_CUDA_SUPPORT = pmpix_query_cuda_support
#pragma weak pmpix_query_cuda_support__ = pmpix_query_cuda_support
#pragma weak pmpix_query_cuda_support_ = pmpix_query_cuda_support
#endif /* Test on name mapping */

#elif defined(HAVE_WEAK_ATTRIBUTE)
#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL pmpix_query_cuda_support__( MPI_Fint * ) __attribute__((weak,alias("PMPIX_QUERY_CUDA_SUPPORT")));
extern FORT_DLL_SPEC void FORT_CALL pmpix_query_cuda_support_( MPI_Fint * ) __attribute__((weak,alias("PMPIX_QUERY_CUDA_SUPPORT")));
extern FORT_DLL_SPEC void FORT_CALL pmpix_query_cuda_support( MPI_Fint * ) __attribute__((weak,alias("PMPIX_QUERY_CUDA_SUPPORT")));

#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPIX_QUERY_CUDA_SUPPORT( MPI_Fint * ) __attribute__((weak,alias("pmpix_query_cuda_support__")));
extern FORT_DLL_SPEC void FORT_CALL pmpix_query_cuda_support_( MPI_Fint * ) __attribute__((weak,alias("pmpix_query_cuda_support__")));
extern FORT_DLL_SPEC void FORT_CALL pmpix_query_cuda_support( MPI_Fint * ) __attribute__((weak,alias("pmpix_query_cuda_support__")));

#elif defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL PMPIX_QUERY_CUDA_SUPPORT( MPI_Fint * ) __attribute__((weak,alias("pmpix_query_cuda_support_")));
extern FORT_DLL_SPEC void FORT_CALL pmpix_query_cuda_support__( MPI_Fint * ) __attribute__((weak,alias("pmpix_query_cuda_support_")));
extern FORT_DLL_SPEC void FORT_CALL pmpix_query_cuda_support( MPI_Fint * ) __attribute__((weak,alias("pmpix_query_cuda_support_")));

#else
extern FORT_DLL_SPEC void FORT_CALL PMPIX_QUERY_CUDA_SUPPORT( MPI_Fint * ) __attribute__((weak,alias("pmpix_query_cuda_support")));
extern FORT_DLL_SPEC void FORT_CALL pmpix_query_cuda_support__( MPI_Fint * ) __attribute__((weak,alias("pmpix_query_cuda_support")));
extern FORT_DLL_SPEC void FORT_CALL pmpix_query_cuda_support_( MPI_Fint * ) __attribute__((weak,alias("pmpix_query_cuda_support")));

#endif /* Test on name mapping */
#endif /* HAVE_MULTIPLE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */

#ifdef F77_NAME_UPPER
#define mpix_query_cuda_support_ PMPIX_QUERY_CUDA_SUPPORT
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_query_cuda_support_ pmpix_query_cuda_support__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_query_cuda_support_ pmpix_query_cuda_support
#else
#define mpix_query_cuda_support_ pmpix_query_cuda_support_
#endif /* Test on name mapping */

#ifdef F77_USE_PMPI
/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings. */
#undef MPIX_Query_cuda_support
#define MPIX_Query_cuda_support PMPIX_Query_cuda_support 
#endif

#else

#ifdef F77_NAME_UPPER
#define mpix_query_cuda_support_ MPIX_QUERY_CUDA_SUPPORT
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpix_query_cuda_support_ mpix_query_cuda_support__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpix_query_cuda_support_ mpix_query_cuda_support
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpix_query_cuda_support_ ( MPI_Fint *ierr ){
    *ierr = MPIX_Query_cuda_support(  );
}
