#!/bin/bash
#
# ParaStation
#
# Copyright (C) 2013-2021 ParTec Cluster Competence Center GmbH, Munich
# Copyright (C) 2021-2026 ParTec AG, Munich
#
# This file may be distributed under the terms of the Q Public License
# as defined in the file LICENSE.QPL included in the packaging of this
# file.

# Parse the xml file $1 generated by "make test" (mpich2/test/mpi/summary.xml) and give a summary
# of the failing tests.

# 'xmlstarlet' on fedora, 'xml' on SuSE
XMLSTARLET="$(which xmlstarlet 2>/dev/null || echo xml)"

(cat $1) |
	"$XMLSTARLET" sel -T  -t -m 'MPITESTRESULTS/MPITEST[STATUS="fail"]' \
	    -v 'concat(WORKDIR,"/",NAME," np=", NP, ":")' \
	    -v 'TESTDIFF' -n -o '-------------------------------------------------' -n \
	    -t -v 'concat(count(MPITESTRESULTS/MPITEST[STATUS="fail"])," tests failed out of ",count(MPITESTRESULTS/MPITEST))'

# Local Variables:
#  compile-command: "./test-summary.sh"
# End:
