#!/bin/bash
#
# (c) 2013-05-22 Jens Hauke <hauke@par-tec.com>
#
# Parse the xml file $1 generated by "make test" (mpich2/test/mpi/summary.xml) and give a summary
# of the failing tests.

# 'xmlstarlet' on fedora, 'xml' on SuSE
XMLSTARLET="$(which xmlstarlet 2>/dev/null || echo xml)"

(cat $1;echo "</MPITESTRESULTS>") |
	"$XMLSTARLET" sel -T  -t -m 'MPITESTRESULTS/MPITEST[STATUS="fail"]' \
	    -v 'concat(WORKDIR,"/",NAME," np=", NP, ":")' \
	    -v 'TESTDIFF' -n -o '-------------------------------------------------' -n \
	    -t -v 'concat(count(MPITESTRESULTS/MPITEST[STATUS="fail"])," tests failed out of ",count(MPITESTRESULTS/MPITEST))'

# Local Variables:
#  compile-command: "./test-summary.sh"
# End:
