#!/bin/bash
#
# ParaStation
#
# Copyright (C) 2010-2021 ParTec Cluster Competence Center GmbH, Munich
# Copyright (C) 2021-2025 ParTec AG, Munich
#
# This file may be distributed under the terms of the Q Public License
# as defined in the file LICENSE.QPL included in the packaging of this
# file.
#

function error() {
    echo "$*" >&2
    exit 1
}


function vecho() {
    [[ -n "${arg_verbose}" ]] && echo "$*" >&2
}


function usage(){
    cat <<EOF
Usage:
  ${BASH_SOURCE[0]} [OPTION]...

Get a version string from the last tag of the version control.

  file: use file \$prjroot/VERSION with content "\${PKG_NAME}-\${VERSION}"

  git: last "git tag" matching the pattern ?*-?*

  --file              force usage of VERSION file
  --git               force usage of git
  --parentdir         force usage of parent dir name

  -r|--prjroot dir    project root (default ".")

  --fmt format        with format:
                      "all"     : print full versionstring (default)
                      "release" : print the release (everything after the first "-")
                      "version" : print the version (everything before the first "-")

  -n|--no-newline     do not output the trailing newline

  --no-dirty          for git: do not add "dirty" for dirty working copies

  --isrelease         test, if version number matches "x.y-r" or "x.y.z-r" with xyzr digits only.

  --suffix            add a custom suffix to the version string instead of the
                      branch name (only works with git)

  -v|--verbose        verbose
  -h, --help          help
EOF
    exit 0
}

arg_prjroot="."
arg_fmt="all"
arg_newline=""
arg_dirty="--dirty=_dirty"

function parse_arg() {
    while [[ $# -gt 0 ]]; do
	case "$1" in
	    --file)		arg_vc="file";;
	    --git)		arg_vc="git";;
	    --parentdir)	arg_vc="parentdir";;
	    -r|--prjroot)	arg_prjroot="$2";shift;;
	    --fmt)		arg_fmt="$2";shift;;
	    -n|--no-newline)	arg_newline="-n";;
	    --isrelease)	arg_isrelease="1"; arg_fmt="none";;
	    --suffix)		arg_suffix="$2";shift;;
	    --no-dirty)		arg_dirty="";;
	    --help|-h)		usage;;
	    --verbose|-v)	arg_verbose=1;;
	    *)			echo "WARNING: unhandled option '$1'";;
	esac
	shift
    done
}


parse_arg "$@"

cd "${arg_prjroot}" || error "'${arg_prjroot}' no such directory. Abort!"

if [[ -z "${arg_vc}" ]]; then
    if [[ -e "VERSION" ]]; then
	arg_vc="file"
    elif [[ -e ".git" ]]; then
	arg_vc="git"
    else
	arg_vc="parentdir_try"
    fi
fi


case "${arg_vc}" in
    file)
	vecho "Tag from VERSION"
	version="$(cat VERSION)"
	version="${version#[a-zA-Z]*-}" # remove optional package name
	;;
    git)
	vecho "Tag from git"
	# retry git-describe without --dirty on error. (pre git-1.6.6 has no --dirty)
	version="$(git describe --tags ${arg_dirty:+"${arg_dirty}"} --always --match "?*-?*" 2>/dev/null ||\
		   git describe --tags --always --match "?*-?*")"
	version="${version#*\/}" # Remove prefix e.g. "sf/"
	if ! git describe --tags --exact-match --always --match "?*-?*" >/dev/null 2>&1; then
	    if [[ -z "${arg_suffix+x}" ]]; then
		# Append the branchname, if not exactly on a tag and branch != master && branch != main
		# This branch is only taken if arg_suffix is not set, i.e., the `--suffix` option is _not_ passed
		branch="$(git symbolic-ref HEAD)"
		branch="${branch/*\/}"
		if [[ "${branch}" == "master" ]] || [[ "${branch}" == "" ]] || [[ "${branch}" == "main" ]]; then
			branch=""
		else
			branch="-${branch}"
		fi
	    elif [[ -z "${arg_suffix}" ]]; then
		# Remove the "branch" suffix if not argument is given (i.e., vcversion [...] --sufix [...])
		branch=""
	    else
		branch="-${arg_suffix}"
	    fi
	    version="$version$branch"
	fi
	;;
    parentdir|parentdir_try)
	vecho "Tag from parent dir name"
	version="${PWD}"
	if [[ -z "${version}" ]]; then
	    version="$(pwd)"
	fi
	version="${version%/}"
	version="${version##*/}" # tail dir name
	version="${version#[a-zA-Z]*-}" # remove optional package name
	case "${version//[^.-]}-${arg_vc}" in # version need a '.' or '-' inside to be a version.
	    -parentdir) error "Can not guess a version string from the parent dir name." ;;
	    -parentdir_try) error "No .git or VERSION found and can not guess a version string from the parent dir name." ;;
	    *) ;; # version string found, continue
	esac
       	;;
    *)
	error "No .git or VERSION found"
	;;
esac

release="${version#*-}"
# If there is no "-" inside version use the default release name "0"
if [[ "${release}" == "${version}" ]]; then release="0"; fi

version="${version%%-*}"

# Allow only [.a-zA-Z0-9] for the version. Replace all others by "_".
version="${version//[^.a-zA-Z0-9]/_}"

# use only rpm release allowed chars. Replace all others by "_".
release="${release//[^a-zA-Z0-9]/_}"

case "${arg_fmt}" in
    version)	echo ${arg_newline:+"${arg_newline}"} "${version}";;
    release)	echo ${arg_newline:+"${arg_newline}"} "${release}";;
    none)	;;
    *)		echo ${arg_newline:+"${arg_newline}"} "${version}-${release}";;
esac

if [[ "${arg_isrelease}" != "1" ]]; then
    :
else
    regexp='^([0-9]+\.){1,2}[0-9]+-[0-9]+(rc[0-9]+)?$' # see FAQ E14
    [[ "${version}-${release}" =~ ${regexp} ]]
fi
