image:
  - Visual Studio 2015
  - Visual Studio 2017

build:
  project: libfabric.sln

configuration:
  - Debug-v140
  - Debug-v141
  - Release-v140
  - Release-v141

matrix:
  exclude:
    - configuration: Debug-v141
      image: Visual Studio 2015
    - configuration: Release-v141
      image: Visual Studio 2015

before_build:
  - ps: .appveyor.ps1 -Verbose

after_build:
  - set PATH=%CD%\x64\%CONFIGURATION%;%PATH%
  - cd ..

before_test:
  - git clone https://github.com/ofiwg/fabtests
  - cd fabtests
  - git checkout -b v1.6.x origin/v1.6.x
  - msbuild fabtests.sln

test_script:
  - set PATH=%CD%\x64\%CONFIGURATION%;%PATH%
  - scripts\runfabtests.cmd
