sudo: false
language: c

os:
  - linux
  - osx

dist: bionic

env:
  - DEVICE=ch3:nemesis
  - DEVICE=ch3:sock
#  - DEVICE=ch4:ofi
#  - DEVICE=ch4:ucx

matrix:
  exclude:
    - os: osx
      env: DEVICE=ch4:ofi
    - os: osx
      env: DEVICE=ch4:ucx

addons:
  apt:
    packages: gfortran libnuma-dev

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then MPICH_FORTRAN=--disable-fortran; fi


script:
  - ./autogen.sh
  - ./configure --prefix=$PWD/i --with-device=$DEVICE $MPICH_FORTRAN
  - make -j2 install
